
-- Time Frame
CREATE TABLE PL_TIME_FRAME
(
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  TIME_FRAME_EDESC    VARCHAR2(100 BYTE)        NOT NULL,
  TIME_FRAME_NDESC    VARCHAR2(400 BYTE)        DEFAULT NULL,
  TIME_FRAME_TYPE     VARCHAR2(20 BYTE)         DEFAULT 'CALENDAR',
  DAYS                NUMBER(3)                 DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)
)

CREATE UNIQUE INDEX PK_TIME_FRAME ON PL_TIME_FRAME
(TIME_FRAME_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX UNQ_TIME_FRAME ON PL_TIME_FRAME
(TIME_FRAME_EDESC, COMPANY_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE PL_TIME_FRAME ADD (
  CHECK (TIME_FRAME_TYPE IN ('CALENDAR', 'DAYS'))
  ENABLE VALIDATE,
  CONSTRAINT PK_TIME_FRAME
  PRIMARY KEY
  (TIME_FRAME_CODE)
  USING INDEX PK_TIME_FRAME
  ENABLE VALIDATE,
  CONSTRAINT UNQ_TIME_FRAME
  UNIQUE (TIME_FRAME_EDESC, COMPANY_CODE)
  USING INDEX UNQ_TIME_FRAME
  ENABLE VALIDATE);
 --End Time Frame
 
 -- Sales Plan
 CREATE TABLE PL_SALES_PLAN
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_EDESC          VARCHAR2(200 BYTE)        NOT NULL,
  PLAN_NDESC          VARCHAR2(400 BYTE)        DEFAULT NULL,
  SALES_QUANTITY      NUMBER(16,2)              DEFAULT NULL,
  SALES_AMOUNT        NUMBER(16,2)              DEFAULT NULL,
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  CALENDAR_TYPE       VARCHAR2(3 BYTE),
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  SALES_PRICE_TYPE    VARCHAR2(50 BYTE),
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE),
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)
)
CREATE UNIQUE INDEX UNQ_SALES_PLAN ON PL_SALES_PLAN
(PLAN_EDESC, TIME_FRAME_CODE, START_DATE, END_DATE)
NOPARALLEL;


CREATE UNIQUE INDEX PK_SALES_PLAN ON PL_SALES_PLAN
(PLAN_CODE)
NOPARALLEL;


ALTER TABLE PL_SALES_PLAN ADD (
  CHECK ( CALENDAR_TYPE IN ('ENG','LOC'))
  ENABLE VALIDATE,
  CONSTRAINT PK_SALES_PLAN
  PRIMARY KEY
  (PLAN_CODE)
  USING INDEX PK_SALES_PLAN
  ENABLE VALIDATE,
  CONSTRAINT UNQ_SALES_PLAN
  UNIQUE (PLAN_EDESC, TIME_FRAME_CODE, START_DATE, END_DATE)
  USING INDEX UNQ_SALES_PLAN
  ENABLE VALIDATE);
--End sales plan

-- sales plan detail
CREATE TABLE PL_SALES_PLAN_DTL
(
  PLAN_CODE            NUMBER(12)               NOT NULL,
  PLAN_DATE            DATE                     NOT NULL,
  PER_DAY_QUANTITY     NUMBER(14,2)             DEFAULT NULL,
  PER_DAY_AMOUNT       NUMBER(14,2)             DEFAULT NULL,
  ITEM_CODE            VARCHAR2(30 BYTE)        DEFAULT NULL,
  CUSTOMER_CODE        VARCHAR2(30 BYTE)        DEFAULT NULL,
  EMPLOYEE_CODE        VARCHAR2(30 BYTE)        DEFAULT NULL,
  DIVISION_CODE        VARCHAR2(30 BYTE)        DEFAULT NULL,
  FREQUENCY_JSON       VARCHAR2(500 BYTE)       DEFAULT NULL,
  SALES_PRICE_APPLIED  NUMBER(16,2)             DEFAULT NULL,
  REMARKS              VARCHAR2(400 BYTE)       DEFAULT NULL,
  COMPANY_CODE         VARCHAR2(30 BYTE),
  BRANCH_CODE          VARCHAR2(30 BYTE),
  CREATED_BY           VARCHAR2(30 BYTE),
  CREATED_DATE         DATE,
  LAST_MODIFIED_BY     VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE   DATE,
  APPROVED_FLAG        CHAR(1 BYTE),
  APPROVED_BY          VARCHAR2(30 BYTE),
  APPROVED_DATE        DATE,
  DELETED_FLAG         CHAR(1 BYTE)
)

CREATE UNIQUE INDEX UNQ_SALES_PLAN_DTL ON PL_SALES_PLAN_DTL
(PLAN_CODE, PLAN_DATE, ITEM_CODE, CUSTOMER_CODE, DIVISION_CODE, 
EMPLOYEE_CODE)
NOPARALLEL;


ALTER TABLE PL_SALES_PLAN_DTL ADD (
  CONSTRAINT UNQ_SALES_PLAN_DTL
  UNIQUE (PLAN_CODE, PLAN_DATE, ITEM_CODE, CUSTOMER_CODE, DIVISION_CODE, EMPLOYEE_CODE)
  USING INDEX UNQ_SALES_PLAN_DTL
  ENABLE VALIDATE);

ALTER TABLE PL_SALES_PLAN_DTL ADD (
  CONSTRAINT FK_SALES_PLAN_DTL 
  FOREIGN KEY (PLAN_CODE) 
  REFERENCES PL_SALES_PLAN (PLAN_CODE)
  ENABLE VALIDATE);  
-- end sales plan detail  

-- master sales plan
CREATE TABLE PL_MASTER_SALES_PLAN
(
  MASTER_PLAN_CODE    NUMBER(12)                NOT NULL,
  MASTER_PLAN_EDESC   VARCHAR2(500 BYTE)        NOT NULL,
  MASTER_PLAN_NDESC   VARCHAR2(500 BYTE)        NOT NULL,
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  CUSTOMER_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  EMPLOYEE_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE),
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)
)
CREATE UNIQUE INDEX PK_MASTER_SALES_PLAN ON PL_MASTER_SALES_PLAN
(MASTER_PLAN_CODE)
NOPARALLEL;


ALTER TABLE PL_MASTER_SALES_PLAN ADD (
  CONSTRAINT PK_MASTER_SALES_PLAN
  PRIMARY KEY
  (MASTER_PLAN_CODE)
  USING INDEX PK_MASTER_SALES_PLAN
  ENABLE VALIDATE);
-- end master sales plan

-- sales plan map
CREATE TABLE PL_SALES_PLAN_MAP
(
  MASTER_PLAN_CODE  NUMBER(12)                  NOT NULL,
  PLAN_CODE         NUMBER(12)                  NOT NULL,
  PARENT_PLAN_CODE  NUMBER(12)                  DEFAULT NULL,
  PLAN_FLAG         CHAR(2 BYTE)                DEFAULT 'SP'
)  

ALTER TABLE PL_SALES_PLAN_MAP ADD (
  CONSTRAINT FK_SALES_PLAN_MAP1 
  FOREIGN KEY (MASTER_PLAN_CODE) 
  REFERENCES PL_MASTER_SALES_PLAN (MASTER_PLAN_CODE)
  ENABLE VALIDATE,
  CONSTRAINT FK_SALES_PLAN_MAP2 
  FOREIGN KEY (MASTER_PLAN_CODE) 
  REFERENCES PL_MASTER_SALES_PLAN (MASTER_PLAN_CODE)
  ENABLE VALIDATE);
-- end of sales plan map  

-- hr employee tree
CREATE TABLE HR_EMPLOYEE_TREE
(
  EMPLOYEE_CODE         VARCHAR2(30 BYTE)       NOT NULL,
  PARENT_EMPLOYEE_CODE  VARCHAR2(30 BYTE)
)

ALTER TABLE HR_EMPLOYEE_TREE ADD COMPANY_CODE  varchar2(30); 
--OR
DROP TABLE HR_EMPLOYEE_TREE CASCADE CONSTRAINTS;

CREATE TABLE HR_EMPLOYEE_TREE
(
  EMPLOYEE_CODE         VARCHAR2(30 BYTE)       NOT NULL,
  PARENT_EMPLOYEE_CODE  VARCHAR2(30 BYTE),
  COMPANY_CODE          VARCHAR2(30 BYTE)
)
-- end hr employee tree

-- sunday april 23, 2017
CREATE TABLE  PL_PREFERENCE_SETUP
(
  COMPANY_CODE         VARCHAR2(30 BYTE),
  BRANCH_CODE          VARCHAR2(30 BYTE),
  ITEM_GROUP_ENTRY       CHAR(1 BYTE) DEFAULT 'N',
  CONSTRAINT PK_PL_PREF_SETUP PRIMARY KEY (COMPANY_CODE,BRANCH_CODE)
);

INSERT INTO PL_PREFERENCE_SETUP(COMPANY_CODE,BRANCH_CODE,ITEM_GROUP_ENTRY) VALUES('01','01.01','Y');

-- This query about creating table PL_COA_PLAN &  PL_COA_PLAN_DTL is from script generated by TOAD,
-- as query was written and implemented in DB by Pramod sir, he could brif about the detail.
CREATE TABLE PL_COA_PLAN
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_EDESC          VARCHAR2(200 BYTE)        NOT NULL,
  PLAN_NDESC          VARCHAR2(400 BYTE)        DEFAULT NULL,
  SALES_AMOUNT        NUMBER(16,2)              DEFAULT NULL,
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  CALENDAR_TYPE       VARCHAR2(3 BYTE)          DEFAULT 'LOC',
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N'
)
CREATE UNIQUE INDEX PK_COA_PLAN ON PL_COA_PLAN
(PLAN_CODE)
NOPARALLEL;

CREATE UNIQUE INDEX UNQ_COA_PLAN ON PL_COA_PLAN
(PLAN_EDESC, START_DATE, END_DATE)
NOPARALLEL;

ALTER TABLE PL_COA_PLAN ADD (
  CONSTRAINT CHK_COA_APPROVED_FLAG
  CHECK (APPROVED_FLAG IN ('Y', 'N')),
  CONSTRAINT CHK_COA_CALENDAR_TYPE
  CHECK (CALENDAR_TYPE IN ('ENG', 'LOC')),
  CONSTRAINT CHK_COA_DELETED_FLAG
  CHECK (DELETED_FLAG IN ('Y', 'N')),
  CONSTRAINT PK_COA_PLAN
  PRIMARY KEY
  (PLAN_CODE)
  USING INDEX PK_COA_PLAN,
  CONSTRAINT UNQ_COA_PLAN
  UNIQUE (PLAN_EDESC, START_DATE, END_DATE)
  USING INDEX UNQ_COA_PLAN);

-- table pl_coa_plan_dtl
CREATE TABLE PL_COA_PLAN_DTL
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_DATE           DATE                      NOT NULL,
  PER_DAY_AMOUNT      NUMBER(14,2)              DEFAULT NULL,
  ACC_CODE            VARCHAR2(30 BYTE)         DEFAULT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  FREQUENCY_JSON      VARCHAR2(500 BYTE)        DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N'
)

CREATE UNIQUE INDEX UNQ_COA_PLAN_DTL ON PL_COA_PLAN_DTL
(PLAN_CODE, PLAN_DATE, ACC_CODE, DIVISION_CODE, BRANCH_CODE, 
COMPANY_CODE)
NOPARALLEL;

ALTER TABLE PL_COA_PLAN_DTL ADD (
  CONSTRAINT CHK_COA_DTL_APP_FLAG
  CHECK (APPROVED_FLAG IN ('Y', 'N')),
  CONSTRAINT CHK_COA_DTL_DEL_FLAG
  CHECK (DELETED_FLAG IN ('Y', 'N')),
  CONSTRAINT UNQ_COA_PLAN_DTL
  UNIQUE (PLAN_CODE, PLAN_DATE, ACC_CODE, DIVISION_CODE, BRANCH_CODE, COMPANY_CODE)
  USING INDEX UNQ_COA_PLAN_DTL);

ALTER TABLE PL_COA_PLAN_DTL ADD (
  CONSTRAINT FK_COA_PLAN_DTL 
  FOREIGN KEY (PLAN_CODE) 
  REFERENCES PL_COA_PLAN (PLAN_CODE));


  alter TABLE  PL_PREFERENCE_SETUP 
add SHOW_CUSTOMER VARCHAR(1 BYTE) DEFAULT 'N';


ALTER TABLE PL_PREFERENCE_SETUP
ADD SHOW_BRANCH VARCHAR(1 BYTE) DEFAULT 'N';


ALTER TABLE PL_PREFERENCE_SETUP
ADD SHOW_EMPLOYEE VARCHAR(1 BYTE) DEFAULT 'N';



SET DEFINE OFF;

Insert into PL_TIME_FRAME
   (TIME_FRAME_CODE, TIME_FRAME_EDESC, TIME_FRAME_TYPE, COMPANY_CODE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, APPROVED_BY, APPROVED_DATE, DELETED_FLAG)
 Values
   (202, 'WEEK', 'CALENDAR', 
    '06', '2', TO_DATE('07/15/2017 13:32:16', 'MM/DD/YYYY HH24:MI:SS'), '2', 
    TO_DATE('07/15/2017 13:32:16', 'MM/DD/YYYY HH24:MI:SS'), '2', TO_DATE('07/15/2017 13:32:16', 'MM/DD/YYYY HH24:MI:SS'), 'N');
    
Insert into PL_TIME_FRAME
   (TIME_FRAME_CODE, TIME_FRAME_EDESC, TIME_FRAME_TYPE, COMPANY_CODE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, APPROVED_BY, APPROVED_DATE, DELETED_FLAG)
 Values
   (204, 'DAILY', 'CALENDAR', 
    '06', '2', TO_DATE('07/15/2017 13:32:16', 'MM/DD/YYYY HH24:MI:SS'), '2', 
    TO_DATE('07/15/2017 13:32:16', 'MM/DD/YYYY HH24:MI:SS'), '2', TO_DATE('07/15/2017 13:32:16', 'MM/DD/YYYY HH24:MI:SS'), 'N');
    
Insert into PL_TIME_FRAME
   (TIME_FRAME_CODE, TIME_FRAME_EDESC, TIME_FRAME_TYPE, COMPANY_CODE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, APPROVED_BY, APPROVED_DATE, DELETED_FLAG)
 Values
   (203, 'MONTH', 'CALENDAR', 
    '06', '2', TO_DATE('07/15/2017 13:32:16', 'MM/DD/YYYY HH24:MI:SS'), '2', 
    TO_DATE('07/15/2017 13:32:16', 'MM/DD/YYYY HH24:MI:SS'), '2', TO_DATE('07/15/2017 13:32:16', 'MM/DD/YYYY HH24:MI:SS'), 'N');
    
    
COMMIT;








---Insert missing table for JGIDatabase
---------------------------prem prkash dhakal Add table form raddission------------------------
CREATE TABLE "JGI8184"."PRICE_SETUP_CHILD" 
   (	"CHILD_ID" NUMBER(*,0), 
	"ITEM_NAME" VARCHAR2(4000 BYTE), 
	"OLD_PRICE" NUMBER(2,0), 
	"NEW_PRICE" NUMBER(2,0), 
	"MASTER_ID" NUMBER(*,0), 
	"STATUS" VARCHAR2(255 BYTE), 
	"ITEM_UNIT" VARCHAR2(255 BYTE), 
	"ITEM_CODE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JGI8184" ;




CREATE TABLE "JGI8184"."PRICE_SETUP_MASTER" 
   (	"MASTER_ID" NUMBER(*,0), 
	"PRICE_LIST_NAME" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER(*,0), 
	"COMPANY" VARCHAR2(100 BYTE), 
	"DATE_ENGLISH" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(255 BYTE), 
	"MODIFIED_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "JGI8184" ;
---------------------------prem prkash dhakal missing table form Adhunik database------------------------
AUDIT_SA_IP_TRANSACTION
CUSTOMER_FOLLOW_UP_DETAILS
SA_SALES_INVOICE_JEWEL
SA_SALES_RETURN_JEWEL
USER_MOBILE_ACCESS
V_DATE_RANGE_ENG
--------------------------------------------------------------------------------------


 
  CREATE TABLE "JGI8184"."AUDIT_SA_IP_TRANSACTION" 
   (	"AUDIT_SR_NO" NUMBER NOT NULL ENABLE, 
	"VOUCHER_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VOUCHER_DATE" DATE NOT NULL ENABLE, 
	"MANUAL_NO" VARCHAR2(100 BYTE), 
	"CUSTOMER_CODE" VARCHAR2(30 BYTE), 
	"SUPPLIER_CODE" VARCHAR2(30 BYTE), 
	"PARTY_NAME" VARCHAR2(300 BYTE), 
	"PARTY_TYPE_CODE" VARCHAR2(5 BYTE), 
	"DEALER_NAME" VARCHAR2(300 BYTE), 
	"BUDGET_FLAG" CHAR(1 BYTE), 
	"SERIAL_NO" NUMBER(5,0), 
	"ITEM_CODE" VARCHAR2(30 BYTE), 
	"ITEM_NAME" VARCHAR2(300 BYTE), 
	"MU_CODE" VARCHAR2(5 BYTE), 
	"QUANTITY" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"CALC_QUANTITY" NUMBER, 
	"CALC_UNIT_PRICE" NUMBER, 
	"CALC_TOTAL_PRICE" NUMBER, 
	"REMARKS" VARCHAR2(200 BYTE), 
	"CREDIT_DAYS" NUMBER(3,0), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE) DEFAULT 'NRS', 
	"EXCHANGE_RATE" NUMBER(16,4) DEFAULT 1, 
	"FROM_LOCATION_CODE" VARCHAR2(30 BYTE), 
	"TO_LOCATION_CODE" VARCHAR2(30 BYTE), 
	"FORM_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"COMPANY_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"BRANCH_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"DELETED_FLAG" CHAR(1 BYTE), 
	"SESSION_ROWID" VARCHAR2(18 BYTE), 
	"BATCH_NO" VARCHAR2(20 BYTE), 
	"MODIFY_DATE" DATE, 
	"MODIFY_BY" VARCHAR2(30 BYTE), 
	"FREE_QTY" NUMBER(14,4), 
	"SMS_FLAG" CHAR(1 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"ROLL_QTY" NUMBER, 
	"PRIORITY_CODE" VARCHAR2(2 BYTE), 
	"PAYMENT_MODE" VARCHAR2(10 BYTE), 
	"MEMBER_SHIP_CARD" VARCHAR2(100 BYTE), 
	"PAYMODE_VALUE" VARCHAR2(30 BYTE), 
	"SHIPPING_ADDRESS" VARCHAR2(500 BYTE), 
	"SHIPPING_CONTACT_NO" VARCHAR2(50 BYTE), 
	"SALES_TYPE_CODE" VARCHAR2(30 BYTE), 
	"EMPLOYEE_CODE" VARCHAR2(30 BYTE), 
	"REASON" VARCHAR2(500 BYTE), 
	"MISC_CODE" VARCHAR2(30 BYTE), 
	"AGENT_CODE" VARCHAR2(10 BYTE), 
	"DIVISION_CODE" VARCHAR2(30 BYTE) DEFAULT '01.01', 
	"NET_GROSS_RATE" NUMBER, 
	"NET_SALES_RATE" NUMBER, 
	"AREA_CODE" NUMBER, 
	"NET_TAXABLE_RATE" NUMBER, 
	"SECOND_QUANTITY" NUMBER, 
	"THIRD_QUANTITY" NUMBER, 
	"PERSON_NAME" VARCHAR2(50 BYTE), 
	"SECTOR_CODE" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"NO_OF_PAX" NUMBER, 
	"SECTOR_NAME" VARCHAR2(50 BYTE), 
	"LC_SERIAL_NO" NUMBER, 
	"EXCISE_AMOUNT" NUMBER, 
	"DISCOUNT_AMOUNT" NUMBER, 
	"VAT_AMOUNT" NUMBER, 
	"IP_ADDRESS" VARCHAR2(50 BYTE), 
	"HOST" VARCHAR2(50 BYTE), 
	"OS_USER" VARCHAR2(50 BYTE), 
	"DB_USER" VARCHAR2(50 BYTE), 
	"ACTION_THROUGH" VARCHAR2(100 BYTE), 
	"ACTION_TYPE" VARCHAR2(50 BYTE), 
	"TABLE_NAME" VARCHAR2(30 BYTE), 
	"ACTION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JGI8184" ;





  
  CREATE TABLE "JGI8184"."CUSTOMER_FOLLOW_UP_DETAILS" 
   (	"FOLLOW_UP_DATE" DATE, 
	"CUSTOMER_CODE" VARCHAR2(10 BYTE), 
	"FOLLOW_UP_DETAILS" VARCHAR2(300 BYTE), 
	"FOLLOWED_BY" VARCHAR2(10 BYTE), 
	"DELETED_FLAG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"COMPANY_CODE" VARCHAR2(2 BYTE), 
	 PRIMARY KEY ("FOLLOW_UP_DATE", "CUSTOMER_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JGI8184"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JGI8184" ;
 


 
  CREATE TABLE "JGI8184"."SA_SALES_INVOICE_JEWEL" 
   (	"SALES_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SALES_DATE" DATE NOT NULL ENABLE, 
	"MANUAL_NO" VARCHAR2(100 BYTE), 
	"CUSTOMER_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"BUDGET_FLAG" CHAR(1 BYTE), 
	"SERIAL_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"ITEM_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"MU_CODE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"CALC_QUANTITY" NUMBER, 
	"CALC_UNIT_PRICE" NUMBER, 
	"CALC_TOTAL_PRICE" NUMBER, 
	"COMPLETED_QUANTITY" NUMBER, 
	"REMARKS" VARCHAR2(200 BYTE), 
	"FORM_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"COMPANY_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"BRANCH_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"DELETED_FLAG" CHAR(1 BYTE), 
	"CREDIT_DAYS" NUMBER(3,0), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"EXCHANGE_RATE" NUMBER(16,4), 
	"SYN_ROWID" VARCHAR2(18 BYTE), 
	"TRACKING_NO" VARCHAR2(16 BYTE), 
	"FROM_LOCATION_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"SESSION_ROWID" VARCHAR2(18 BYTE), 
	"BATCH_NO" VARCHAR2(20 BYTE), 
	"MODIFY_DATE" DATE, 
	"MODIFY_BY" VARCHAR2(30 BYTE), 
	"FREE_QTY" NUMBER(14,4), 
	"PARTY_TYPE_CODE" VARCHAR2(5 BYTE), 
	"SMS_FLAG" CHAR(1 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"ROLL_QTY" NUMBER, 
	"PRIORITY_CODE" VARCHAR2(2 BYTE), 
	"PAYMENT_MODE" VARCHAR2(10 BYTE), 
	"MEMBER_SHIP_CARD" VARCHAR2(100 BYTE), 
	"PAYMODE_VALUE" VARCHAR2(30 BYTE), 
	"SHIPPING_ADDRESS" VARCHAR2(500 BYTE), 
	"SHIPPING_CONTACT_NO" VARCHAR2(50 BYTE), 
	"SALES_TYPE_CODE" VARCHAR2(30 BYTE), 
	"EMPLOYEE_CODE" VARCHAR2(30 BYTE), 
	"REASON" VARCHAR2(500 BYTE), 
	"MISC_CODE" VARCHAR2(30 BYTE), 
	"AGENT_CODE" VARCHAR2(10 BYTE), 
	"DIVISION_CODE" VARCHAR2(30 BYTE), 
	"NET_GROSS_RATE" NUMBER, 
	"NET_SALES_RATE" NUMBER, 
	"AREA_CODE" NUMBER, 
	"NET_TAXABLE_RATE" NUMBER, 
	"SECOND_QUANTITY" NUMBER, 
	"THIRD_QUANTITY" NUMBER, 
	"PERSON_NAME" VARCHAR2(50 BYTE), 
	"SECTOR_CODE" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"NO_OF_PAX" NUMBER, 
	"SECTOR_NAME" VARCHAR2(50 BYTE), 
	"LC_SERIAL_NO" NUMBER, 
	"EXCISE_AMOUNT" NUMBER, 
	"DISCOUNT_AMOUNT" NUMBER, 
	"VAT_AMOUNT" NUMBER, 
	"EXCISE_AMOUNTII" NUMBER, 
	"BD_AMT" NUMBER, 
	"PURITY" NUMBER, 
	"GROSS_WEIGHT" NUMBER, 
	"LESS_STONE" NUMBER, 
	"NET_WEIGHT" NUMBER, 
	"WASTAGE" NUMBER, 
	"TOTAL_WEIGHT" NUMBER, 
	"AMOUNT" NUMBER, 
	"MAKING" NUMBER, 
	"STONE_WEIGHT" NUMBER, 
	"STONE_AMOUNT" NUMBER, 
	"DIAMOND_CARAT" NUMBER, 
	"DIAMOND_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JGI8184" ;
 




   CREATE TABLE "JGI8184"."SA_SALES_RETURN_JEWEL" 
   (	"RETURN_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RETURN_DATE" DATE NOT NULL ENABLE, 
	"MANUAL_NO" VARCHAR2(100 BYTE), 
	"CUSTOMER_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"BUDGET_FLAG" CHAR(1 BYTE), 
	"SERIAL_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"ITEM_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"MU_CODE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"CALC_QUANTITY" NUMBER, 
	"CALC_UNIT_PRICE" NUMBER, 
	"CALC_TOTAL_PRICE" NUMBER, 
	"COMPLETED_QUANTITY" NUMBER, 
	"REMARKS" VARCHAR2(200 BYTE), 
	"FORM_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"COMPANY_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"BRANCH_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"DELETED_FLAG" CHAR(1 BYTE), 
	"CREDIT_DAYS" NUMBER(3,0), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"EXCHANGE_RATE" NUMBER(16,4), 
	"SYN_ROWID" VARCHAR2(18 BYTE), 
	"TRACKING_NO" VARCHAR2(16 BYTE), 
	"FROM_LOCATION_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"SESSION_ROWID" VARCHAR2(18 BYTE), 
	"BATCH_NO" VARCHAR2(20 BYTE), 
	"MODIFY_DATE" DATE, 
	"MODIFY_BY" VARCHAR2(30 BYTE), 
	"FREE_QTY" NUMBER(14,4), 
	"PARTY_TYPE_CODE" VARCHAR2(5 BYTE), 
	"SMS_FLAG" CHAR(1 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"ROLL_QTY" NUMBER, 
	"PRIORITY_CODE" VARCHAR2(2 BYTE), 
	"PAYMENT_MODE" VARCHAR2(10 BYTE), 
	"MEMBER_SHIP_CARD" VARCHAR2(100 BYTE), 
	"PAYMODE_VALUE" VARCHAR2(30 BYTE), 
	"SHIPPING_ADDRESS" VARCHAR2(500 BYTE), 
	"SHIPPING_CONTACT_NO" VARCHAR2(50 BYTE), 
	"SALES_TYPE_CODE" VARCHAR2(30 BYTE), 
	"EMPLOYEE_CODE" VARCHAR2(30 BYTE), 
	"REASON" VARCHAR2(500 BYTE), 
	"MISC_CODE" VARCHAR2(30 BYTE), 
	"AGENT_CODE" VARCHAR2(10 BYTE), 
	"DIVISION_CODE" VARCHAR2(30 BYTE), 
	"NET_GROSS_RATE" NUMBER, 
	"NET_SALES_RATE" NUMBER, 
	"AREA_CODE" NUMBER, 
	"NET_TAXABLE_RATE" NUMBER, 
	"SECOND_QUANTITY" NUMBER, 
	"THIRD_QUANTITY" NUMBER, 
	"PERSON_NAME" VARCHAR2(50 BYTE), 
	"SECTOR_CODE" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"NO_OF_PAX" NUMBER, 
	"SECTOR_NAME" VARCHAR2(50 BYTE), 
	"LC_SERIAL_NO" NUMBER, 
	"EXCISE_AMOUNT" NUMBER, 
	"DISCOUNT_AMOUNT" NUMBER, 
	"VAT_AMOUNT" NUMBER, 
	"EXCISE_AMOUNTII" NUMBER, 
	"BD_AMT" NUMBER, 
	"PURITY" NUMBER, 
	"GROSS_WEIGHT" NUMBER, 
	"LESS_STONE" NUMBER, 
	"NET_WEIGHT" NUMBER, 
	"WASTAGE" NUMBER, 
	"TOTAL_WEIGHT" NUMBER, 
	"AMOUNT" NUMBER, 
	"MAKING" NUMBER, 
	"STONE_WEIGHT" NUMBER, 
	"STONE_AMOUNT" NUMBER, 
	"DIAMOND_CARAT" NUMBER, 
	"DIAMOND_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JGI8184" ;
 



 
  CREATE TABLE "JGI8184"."USER_MOBILE_ACCESS" 
   (	"USER_NO" NUMBER, 
	"REPORTS" VARCHAR2(50 BYTE), 
	"ACCES" CHAR(1 BYTE), 
	"VIU" CHAR(1 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"MODULE" VARCHAR2(50 BYTE), 
	"COMPANY_CODE" VARCHAR2(2 BYTE), 
	 PRIMARY KEY ("USER_NO", "REPORTS", "COMPANY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JGI8184"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JGI8184" ;






    CREATE TABLE "JGI8184"."V_DATE_RANGE_ENG" 
   (	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"RANGENAME" VARCHAR2(12 BYTE), 
	"SORTORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JGI8184" ;







---------------------------kushal Add table for item mapping------------------------
CREATE TABLE IP_ITEM_ATTRIBUTE_SETUP
(
  ATTRIBUTE_CODE      VARCHAR2(30 BYTE)         NOT NULL,
  ATTRIBUTE_EDESC     VARCHAR2(100 BYTE)        NOT NULL,
  ATTRIBUTE_NDESC     VARCHAR2(100 BYTE),
  PRE_ATTRIBUTE_CODE  VARCHAR2(30 BYTE)         NOT NULL,
  REMARKS             VARCHAR2(200 BYTE),
  COMPANY_CODE        VARCHAR2(30 BYTE)         NOT NULL,
  GROUP_SKU_FLAG      CHAR(1 BYTE)              NOT NULL,
  CREATED_BY          VARCHAR2(30 BYTE)         NOT NULL,
  CREATED_DATE        DATE                      NOT NULL,
  DELETED_FLAG        CHAR(1 BYTE),
  DELETED_DATE        DATE,
  DELETED_BY          VARCHAR2(30 BYTE),
  SYN_ROWID           VARCHAR2(18 BYTE),
  MODIFY_DATE         DATE,
  MODIFY_BY           VARCHAR2(30 BYTE)
);

ALTER TABLE IP_ITEM_ATTRIBUTE_SETUP
ADD CONSTRAINT pk_IP_ITEM_ATTRIBUTE_SETUP PRIMARY KEY(ATTRIBUTE_CODE, COMPANY_CODE);

CREATE TABLE IP_ITEM_ATTRIBUTE_MAP
(
  ITEM_CODE       VARCHAR2(30 BYTE)             NOT NULL,
  ATTRIBUTE_CODE  VARCHAR2(30 BYTE)             NOT NULL,
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_BY      VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_DATE    DATE                          NOT NULL,
  DELETED_FLAG    CHAR(1 BYTE)                  DEFAULT 'N'
);

ALTER TABLE IP_ITEM_ATTRIBUTE_MAP
ADD CONSTRAINT pk_IP_ITEM_ATTRIBUTE_MAP PRIMARY KEY(ATTRIBUTE_CODE, ITEM_CODE, COMPANY_CODE);

-- Kushal Tiwari -- 2025-06-04 --
INSERT into WEB_MENU_MANAGEMENT
    (MENU_NO, MENU_EDESC, MENU_OBJECT_NAME, MODULE_CODE, FULL_PATH, VIRTUAL_PATH, ICON_PATH, GROUP_SKU_FLAG, PRE_MENU_NO, COMPANY_CODE, CREATED_BY, CREATED_DATE, ORDERBY, MODULE_ABBR, COLOR)
Values 
    ('05.32', 'Attribute', 'Attribute', '05', 
    '/DocumentTemplate/Home/Index#!DT/AttributeSetup', '/DocumentTemplate/Home/Index#!DT/AttributeSetup', 'fa fa-recycle', 'I', '00', 
    '03', '03',sysdate , 32, 'COL', '#808080   ');

INSERT INTO WEB_MENU_CONTROL
    (USER_NO, MENU_NO, ACCESS_FLAG, COMPANY_CODE, CREATED_BY, CREATED_DATE)
VALUES(60747, '05.32', 'Y', '03', '60747', sysdate);

CREATE TABLE IP_ITEM_ATTRIBUTE_SETUP
(
  ATTRIBUTE_CODE      VARCHAR2(30 BYTE)         NOT NULL,
  ATTRIBUTE_EDESC     VARCHAR2(100 BYTE)        NOT NULL,
  ATTRIBUTE_NDESC     VARCHAR2(100 BYTE),
  PRE_ATTRIBUTE_CODE  VARCHAR2(30 BYTE)         NOT NULL,
  REMARKS             VARCHAR2(200 BYTE),
  COMPANY_CODE        VARCHAR2(30 BYTE)         NOT NULL,
  GROUP_SKU_FLAG      CHAR(1 BYTE)              NOT NULL,
  CREATED_BY          VARCHAR2(30 BYTE)         NOT NULL,
  CREATED_DATE        DATE                      NOT NULL,
  DELETED_FLAG        CHAR(1 BYTE),
  DELETED_DATE        DATE,
  DELETED_BY          VARCHAR2(30 BYTE),
  SYN_ROWID           VARCHAR2(18 BYTE),
  MODIFY_DATE         DATE,
  MODIFY_BY           VARCHAR2(30 BYTE)
);

ALTER TABLE IP_ITEM_ATTRIBUTE_SETUP
ADD CONSTRAINT pk_IP_ITEM_ATTRIBUTE_SETUP (ATTRIBUTE_CODE, COMPANY_CODE);

CREATE TABLE IP_ITEM_ATTRIBUTE_MAP
(
  ITEM_CODE       VARCHAR2(30 BYTE)             NOT NULL,
  ATTRIBUTE_CODE  VARCHAR2(30 BYTE)             NOT NULL,
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_BY      VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_DATE    DATE                          NOT NULL,
  DELETED_FLAG    CHAR(1 BYTE)                  DEFAULT 'N'
);

ALTER TABLE IP_ITEM_ATTRIBUTE_MAP
ADD CONSTRAINT pk_IP_ITEM_ATTRIBUTE_MAP PRIMARY KEY(ATTRIBUTE_CODE, ITEM_CODE, COMPANY_CODE);

-- Kushal Tiwari -- 2025-06-16 --
ALTER TABLE IP_ITEM_STORAGE_SETUP
MODIFY MU_CODE VARCHAR2(10 Byte);

-- Kushal Tiwari -- 2025-06-20 --
CREATE TABLE SA_CUSTOMER_OWNER_FILES (
    COMPANY_CODE        VARCHAR2(20)     NOT NULL,
    CUSTOMER_CODE       VARCHAR2(50)     NOT NULL,
    OWNER_NAME          VARCHAR2(100)    NOT NULL,
    FILE_COLUMN_NAME    VARCHAR2(50)     NOT NULL,
    ORIGINAL_FILENAME   VARCHAR2(255)    NOT NULL,
    STORED_FILENAME     VARCHAR2(255)    NOT NULL,
    FILE_URL            VARCHAR2(500)    NOT NULL,

    CREATED_BY          VARCHAR2(100),
    CREATED_DATE        TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY         VARCHAR2(100),
    MODIFIED_DATE       TIMESTAMP,
    DELETED_BY          VARCHAR2(100),
    DELETED_DATE        TIMESTAMP,
    DELETED_FLAG        CHAR(1)          DEFAULT 'N',

    CONSTRAINT PK_CUSTOMER_OWNER_FILES PRIMARY KEY (
        COMPANY_CODE,
        CUSTOMER_CODE,
        OWNER_NAME,
        FILE_COLUMN_NAME
    )
);


CREATE TABLE JGI8182.SA_CUSTOMER_ITEM_MAP
(
  CUSTOMER_CODE VARCHAR2(30 BYTE),
  ITEM_CODE VARCHAR2(30 BYTE),
  REMARKS             VARCHAR2(200 BYTE),
  COMPANY_CODE        VARCHAR2(30 BYTE)         NOT NULL,
  CREATED_BY          VARCHAR2(30 BYTE)         NOT NULL,
  CREATED_DATE        DATE                      NOT NULL,
  DELETED_FLAG        CHAR(1 BYTE),
  DELETED_DATE        DATE,
  DELETED_BY          VARCHAR2(30 BYTE),
  SYN_ROWID           VARCHAR2(18 BYTE),
  MODIFY_DATE         DATE,
  MODIFY_BY           VARCHAR2(30 BYTE)
)

CREATE TABLE JGI8182.IP_SUPPLIER_ITEM_MAP
(
  SUPPLIER_CODE  VARCHAR2(30 BYTE),
  ITEM_CODE      VARCHAR2(30 BYTE),
  REMARKS        VARCHAR2(200 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  DELETED_DATE   DATE,
  DELETED_BY     VARCHAR2(30 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE)
)
TABLESPACE FY8182

ALTER TABLE SA_CUSTOMER_ITEM_MAP
ADD CONSTRAINT pk_SA_CUSTOMER_ITEM_MAP PRIMARY KEY (CUSTOMER_CODE, ITEM_CODE, COMPANY_CODE);

ALTER TABLE IP_SUPPLIER_ITEM_MAP
ADD CONSTRAINT pk_IP_SUPPLIER_ITEM_MAP PRIMARY KEY (SUPPLIER_CODE, ITEM_CODE, COMPANY_CODE);

-- Kushal Tiwari -- 2025-07-02 --
ALTER TABLE PREFERENCE_SETUP
ADD (GRNI_ACC_CODE VARCHAR2(30 BYTE));

-- Kushal Tiwari -- 2025-07-04 --
CREATE TABLE JGI8182.IP_SUPPLIER_BANK_DETAIL_MAP
(
  SUPPLIER_CODE  VARCHAR2(30 BYTE),
  BANK_NAME      VARCHAR2(30 BYTE),
  BANK_BRANCH        VARCHAR2(200 BYTE),
  BANK_ACC_NO       VARCHAR2(200 BYTE),
  ACC_CODE          VARCHAR2(30 BYTE),
  ACC_EDESC         VARCHAR2(200 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  DELETED_DATE   DATE,
  DELETED_BY     VARCHAR2(30 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE)
)
TABLESPACE FY8182

CREATE TABLE JGI8182.SA_CUSTOMER_BANK_DETAIL_MAP
(
  CUSTOMER_CODE  VARCHAR2(30 BYTE),
  BANK_NAME      VARCHAR2(30 BYTE),
  BANK_BRANCH        VARCHAR2(200 BYTE),
  BANK_ACC_NO       VARCHAR2(200 BYTE),
  ACC_CODE          VARCHAR2(30 BYTE),
  ACC_EDESC         VARCHAR2(200 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  DELETED_DATE   DATE,
  DELETED_BY     VARCHAR2(30 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE)
)
TABLESPACE FY8182

/*sashi*/
DROP TABLE BHPL8182.IP_ITEM_QC_TESTING CASCADE CONSTRAINTS;

CREATE TABLE BHPL8182.IP_ITEM_QC_TESTING
(
  ITEM_CODE       VARCHAR2(30 BYTE)             NOT NULL,
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_BY      VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_DATE    DATE                          NOT NULL,
  DELETED_FLAG    CHAR(1 BYTE),
  MODIFY_DATE     DATE,
  MODIFY_BY       VARCHAR2(30 BYTE),
  SERIAL_NO       VARCHAR2(10 BYTE),
  SUPPLIER_CODE           VARCHAR2(30 BYTE),
  BATCH_NO           VARCHAR2(20 BYTE),
  GSM           VARCHAR2(20 BYTE),
  WIDTH           VARCHAR2(20 BYTE),
  STRENGTH           VARCHAR2(20 BYTE),
  THICKNESS           VARCHAR2(20 BYTE),
  ACTUAL_GSM           VARCHAR2(20 BYTE),
  ACTUAL_WIDTH           VARCHAR2(20 BYTE),
  ACTUAL_STRENGTH           VARCHAR2(20 BYTE),
  ACTUAL_THICKNESS           VARCHAR2(20 BYTE),
  REMARKS         VARCHAR2(200 BYTE)
)


DROP TABLE BHPL8182.IP_ITEM_DAILY_WASTAGE CASCADE CONSTRAINTS;

CREATE TABLE BHPL8182.IP_ITEM_DAILY_WASTAGE
(
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE),
  SERIAL_NO      VARCHAR2(10 BYTE),
  FORM_CODE      VARCHAR2(10 BYTE)              NOT NULL,
  WASTAGE_EDATE   DATE,
  WASTAGE_NDATE   VARCHAR2(20 BYTE),
  WASTAGE_VALUE  VARCHAR2(20 BYTE)
)

DROP TABLE BHPL8182.PRE_DISPATCH_INSPECTION CASCADE CONSTRAINTS;

CREATE TABLE BHPL8182.PRE_DISPATCH_INSPECTION
(
  TIME_PERIOD             VARCHAR2(30 BYTE)     NOT NULL,
  ITEM_CODE               VARCHAR2(30 BYTE)     NOT NULL,
  BATCH_NO                VARCHAR2(20 BYTE),
  LOOSE_PRODUCT_SAMPLE    VARCHAR2(30 BYTE),
  LOOSE_PRODUCT_DEFECT    VARCHAR2(30 BYTE),
  UNSEALED_PACKET_SAMPLE  VARCHAR2(30 BYTE),
  UNSEALED_PACKET_DEFECT  VARCHAR2(30 BYTE),
  SEALED_PACKET_SAMPLE    VARCHAR2(30 BYTE),
  SEALED_PACKET_DEFECT    VARCHAR2(30 BYTE),
  BAG_SAMPLE              VARCHAR2(30 BYTE),
  BAG_DEFECT              VARCHAR2(30 BYTE),
  WRAPPER_SAMPLE          VARCHAR2(30 BYTE),
  WRAPPER_DEFECT          VARCHAR2(30 BYTE),
  REMARKS                 VARCHAR2(200 BYTE),
  COMPANY_CODE            VARCHAR2(30 BYTE)     NOT NULL,
  BRANCH_CODE             VARCHAR2(30 BYTE)     NOT NULL,
  CREATED_BY              VARCHAR2(30 BYTE)     NOT NULL,
  CREATED_DATE            DATE                  NOT NULL,
  DELETED_FLAG            CHAR(1 BYTE),
  MODIFY_DATE             DATE,
  MODIFY_BY               VARCHAR2(30 BYTE),
  SERIAL_NO               VARCHAR2(10 BYTE),
  FORM_CODE               VARCHAR2(10 BYTE)     NOT NULL
)



DROP TABLE BHPL8182.GLOBAL_PRODUCTS_TRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE BHPL8182.GLOBAL_PRODUCTS_TRANSACTION
(
  TRANSACTION_NO             VARCHAR2(20 BYTE)  NOT NULL,
  ITEM_CODE                  VARCHAR2(30 BYTE)  NOT NULL,
  REFERENCE_NO               VARCHAR2(20 BYTE)  NOT NULL,
  SERIAL_NO                  NUMBER(5)          NOT NULL,
  FORM_CODE                  VARCHAR2(10 BYTE)  NOT NULL,
  COMPANY_CODE               VARCHAR2(30 BYTE)  NOT NULL,
  BRANCH_CODE                VARCHAR2(30 BYTE)  NOT NULL,
  CREATED_BY                 VARCHAR2(30 BYTE)  NOT NULL,
  CREATED_DATE               DATE               NOT NULL,
  DELETED_FLAG               CHAR(1 BYTE),
  SYN_ROWID                  VARCHAR2(18 BYTE),
  SESSION_ROWID              VARCHAR2(18 BYTE),
  VEHICLE_NO                 VARCHAR2(20 BYTE),
  PARTY_NAME                 VARCHAR2(30 BYTE),
  ADDRESS                    VARCHAR2(30 BYTE),
  BILL_NO                    VARCHAR2(20 BYTE),
  GATE_OR_GRN_NO             VARCHAR2(20 BYTE),
  PHYSICAL_TEST_RAWMATERIAL  VARCHAR2(30 BYTE),
  WEIGHT                     VARCHAR2(20 BYTE),
  MOISTURE                   VARCHAR2(20 BYTE),
  TEMPERATURE                VARCHAR2(20 BYTE),
  WET                        VARCHAR2(20 BYTE),
  FUNGUS                     VARCHAR2(20 BYTE),
  DUST                       VARCHAR2(20 BYTE),
  GRADING                    VARCHAR2(20 BYTE),
  SMELL                      VARCHAR2(20 BYTE),
  COLOR                      VARCHAR2(20 BYTE),
  PIECES                     VARCHAR2(20 BYTE),
  IMMATURITY_OF_GRAINS       VARCHAR2(20 BYTE),
  OTHER_ITEMS                VARCHAR2(30 BYTE),
  ROTTEN_HOLED               VARCHAR2(30 BYTE),
  DAMAGED                    VARCHAR2(30 BYTE),
  BROKEN                     VARCHAR2(30 BYTE),
  HUSK                       VARCHAR2(30 BYTE),
  OVERTOASTED                VARCHAR2(30 BYTE),
  USEABLE                    VARCHAR2(30 BYTE),
  UNUSEABLE                  VARCHAR2(30 BYTE),
  FAT                        VARCHAR2(20 BYTE),
  QUALITY_OF_GOODS           VARCHAR2(20 BYTE),
  EXCELLENT                  VARCHAR2(20 BYTE),
  GREAT                      VARCHAR2(30 BYTE),
  GOODS_NORMAL               VARCHAR2(30 BYTE),
  WAREHOUSE                  VARCHAR2(30 BYTE),
  SILO                       VARCHAR2(30 BYTE),
  GHAN                       VARCHAR2(30 BYTE),
  PROTEIN                    VARCHAR2(30 BYTE),
  QUALITY_OF_FIREWOOD        VARCHAR2(30 BYTE),
  PRODUCT_SIZE               VARCHAR2(30 BYTE),
  PRODUCT_TYPE               VARCHAR2(30 BYTE),
  DEDUCT_IN_BAG              VARCHAR2(30 BYTE),
  NET_WEIGHT                 VARCHAR2(30 BYTE),
  ISPLASTIC_BAG              CHAR(1 BYTE),
  ISJUTE_BAG                 CHAR(1 BYTE),
  ISPLASTIC_WEIGHT           CHAR(1 BYTE),
  ISJUTE_WEIGHT              CHAR(1 BYTE),
  PRODUCT_REMARKS            VARCHAR2(200 BYTE),
  REMARKS                    VARCHAR2(200 BYTE),
  UNLOAD_UNIT                VARCHAR2(30 BYTE),
  MODIFY_DATE                DATE,
  MODIFY_BY                  VARCHAR2(30 BYTE),
  CHECKED_BY                 VARCHAR2(30 BYTE),
  AUTHORISED_BY              VARCHAR2(30 BYTE)
)

ALTER TABLE GLOBAL_PRODUCTS_TRANSACTION
ADD (
    DEDUCT_IN_PLASTIC VARCHAR2(30 BYTE),
    DEDUCT_IN_JUTE    VARCHAR2(30 BYTE)
);

DROP TABLE BHPL8182.GLOBAL_WEIGHT_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE BHPL8182.GLOBAL_WEIGHT_DETAILS
(
  GLOBAL_WEIGHT_NO   VARCHAR2(20 BYTE)          NOT NULL,
  SERIAL_NO          NUMBER(5)                  NOT NULL,
  FORM_CODE          VARCHAR2(10 BYTE)          NOT NULL,
  COMPANY_CODE       VARCHAR2(30 BYTE)          NOT NULL,
  BRANCH_CODE        VARCHAR2(30 BYTE)          NOT NULL,
  CREATED_BY         VARCHAR2(30 BYTE)          NOT NULL,
  CREATED_DATE       DATE                       NOT NULL,
  DELETED_FLAG       CHAR(1 BYTE),
  SYN_ROWID          VARCHAR2(18 BYTE),
  SESSION_ROWID      VARCHAR2(18 BYTE),
  FIRST_WEIGHT       VARCHAR2(18 BYTE),
  SECOND_WEIGHT      VARCHAR2(18 BYTE),
  NET_WEIGHT         VARCHAR2(18 BYTE),
  CHALLAN_WEIGHT     VARCHAR2(18 BYTE),
  WEIGHT_DIFFERENCE  VARCHAR2(18 BYTE),
  REMARKS            VARCHAR2(200 BYTE),
  MODIFY_DATE        DATE,
  MODIFY_BY          VARCHAR2(30 BYTE),
  CHECKED_BY         VARCHAR2(30 BYTE),
  AUTHORISED_BY      VARCHAR2(30 BYTE)
)


DROP TABLE BHPL8182.GLOBAL_UNLOADED_CHHALLI CASCADE CONSTRAINTS;

CREATE TABLE BHPL8182.GLOBAL_UNLOADED_CHHALLI
(
  GLOBAL_UNLOADED_NO  VARCHAR2(20 BYTE)         NOT NULL,
  SERIAL_NO           NUMBER(5)                 NOT NULL,
  FORM_CODE           VARCHAR2(10 BYTE)         NOT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE)         NOT NULL,
  BRANCH_CODE         VARCHAR2(30 BYTE)         NOT NULL,
  CREATED_BY          VARCHAR2(30 BYTE)         NOT NULL,
  CREATED_DATE        DATE                      NOT NULL,
  DELETED_FLAG        CHAR(1 BYTE),
  SYN_ROWID           VARCHAR2(18 BYTE),
  FIRST_CHHALLI       VARCHAR2(18 BYTE),
  SECOND_CHHALLI      VARCHAR2(18 BYTE),
  THIRD_CHHALLI       VARCHAR2(18 BYTE),
  FOURTH_CHHALLI      VARCHAR2(18 BYTE),
  FIFTH_CHHALLI       VARCHAR2(18 BYTE),
  SIXTH_CHHALLI       VARCHAR2(18 BYTE),
  SEVENTH_CHHALLI     VARCHAR2(18 BYTE),
  EIGHTH_CHHALLI      VARCHAR2(18 BYTE),
  NINETH_CHHALLI      VARCHAR2(18 BYTE),
  TENTH_CHHALLI       VARCHAR2(18 BYTE),
  ELEVEN_CHHALLI      VARCHAR2(18 BYTE),
  TWELVE_CHHALLI      VARCHAR2(18 BYTE),
  TOTAL               VARCHAR2(18 BYTE),
  REMARKS             VARCHAR2(200 BYTE),
  MODIFY_DATE         DATE,
  MODIFY_BY           VARCHAR2(30 BYTE),
  CHECKED_BY          VARCHAR2(30 BYTE),
  AUTHORISED_BY       VARCHAR2(30 BYTE)
)


DROP TABLE BHPL8182.GLOBAL_DAKHILA_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE BHPL8182.GLOBAL_DAKHILA_DETAILS
(
  GLOBAL_DAKHILA_NO  VARCHAR2(20 BYTE)          NOT NULL,
  SERIAL_NO          NUMBER(5)                  NOT NULL,
  FORM_CODE          VARCHAR2(10 BYTE)          NOT NULL,
  COMPANY_CODE       VARCHAR2(30 BYTE)          NOT NULL,
  BRANCH_CODE        VARCHAR2(30 BYTE)          NOT NULL,
  CREATED_BY         VARCHAR2(30 BYTE)          NOT NULL,
  CREATED_DATE       DATE                       NOT NULL,
  DELETED_FLAG       CHAR(1 BYTE),
  SYN_ROWID          VARCHAR2(18 BYTE),
  ENTRY_NO           VARCHAR2(18 BYTE),
  BILL_NO            VARCHAR2(18 BYTE),
  CHALAN_NO          VARCHAR2(18 BYTE),
  ITEM               VARCHAR2(18 BYTE),
  TOTAL_BAG          VARCHAR2(18 BYTE),
  WEIGHT             VARCHAR2(18 BYTE),
  REMARKS            VARCHAR2(200 BYTE),
  MODIFY_DATE        DATE,
  MODIFY_BY          VARCHAR2(30 BYTE),
  CHECKED_BY         VARCHAR2(30 BYTE),
  AUTHORISED_BY      VARCHAR2(30 BYTE)
)


ALTER TABLE GLOBAL_PRODUCTS_TRANSACTION
ADD CONSTRAINT PK_PRODUCTS_TRANSACTION
PRIMARY KEY (TRANSACTION_NO);

ALTER TABLE GLOBAL_WEIGHT_DETAILS
ADD CONSTRAINT FK_GLOBAL_WEIGHT_DETAILS
FOREIGN KEY (GLOBAL_WEIGHT_NO)
REFERENCES GLOBAL_PRODUCTS_TRANSACTION (TRANSACTION_NO);

ALTER TABLE GLOBAL_UNLOADED_CHHALLI
ADD CONSTRAINT FK_GLOBAL_UNLOADED_CHHALLI
FOREIGN KEY (GLOBAL_UNLOADED_NO)
REFERENCES GLOBAL_PRODUCTS_TRANSACTION (TRANSACTION_NO);

ALTER TABLE GLOBAL_DAKHILA_DETAILS
ADD CONSTRAINT FK_GLOBAL_DAKHILA_DETAILS
FOREIGN KEY (GLOBAL_DAKHILA_NO)
REFERENCES GLOBAL_PRODUCTS_TRANSACTION (TRANSACTION_NO);

ALTER TABLE GLOBAL_PRODUCTS_TRANSACTION 
ADD (DEDUCT_IN_WT VARCHAR2(30 BYTE));

CREATE TABLE Product_Type (
    ID VARCHAR2(30 BYTE)    NOT NULL,
    PRODUCT_EDESC VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_Product_Type
PRIMARY KEY (ID)
);

ALTER TABLE ip_item_master_setup 
ADD (
    Target    VARCHAR2(120 BYTE),
    Tolerence VARCHAR2(120 BYTE)
);
ALTER TABLE ip_item_master_setup 
ADD (
    Product_Type    VARCHAR2(120 BYTE)
);

CREATE TABLE Product_Type_Map (
    ID             VARCHAR2(30 BYTE) NOT NULL,
    PRODUCT_TYPE_ID VARCHAR2(30 BYTE) NOT NULL,
    PRODUCT_ID      VARCHAR2(30 BYTE) NOT NULL,
    COMPANY_CODE    VARCHAR2(30 BYTE) NOT NULL,
    BRANCH_CODE     VARCHAR2(30 BYTE) NOT NULL,
    CREATED_BY      VARCHAR2(30 BYTE) NOT NULL,
    CREATED_DATE    DATE NOT NULL,
    DELETED_FLAG    CHAR(1 BYTE),
    MODIFY_DATE     DATE,
    MODIFY_BY       VARCHAR2(30 BYTE),

    CONSTRAINT PK_Product_Type_Map PRIMARY KEY (ID),

    CONSTRAINT FK_PRODUCT_TYPE FOREIGN KEY (PRODUCT_TYPE_ID)
        REFERENCES PRODUCT_TYPE (ID)

    -- CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID)
       -- REFERENCES ip_item_master_setup (ITEM_CODE)
);


commit;


select * from GLOBAL_Weight_Details;
select * from GLOBAL_UNLOADED_CHHALLI;
select * from GLOBAL_DAKHILA_DETAILS;
select * from GLOBAL_PRODUCTS_TRANSACTION;

DROP TABLE BHPL8182.IP_ITEM_QC_SETUP CASCADE CONSTRAINTS;

CREATE TABLE BHPL8182.IP_ITEM_QC_SETUP
(
  ITEM_CODE       VARCHAR2(30 BYTE)             NOT NULL,
  QC_CODE         VARCHAR2(10 BYTE)             NOT NULL,
  QC_EDESC        VARCHAR2(100 BYTE)            NOT NULL,
  QC_NDESC        VARCHAR2(100 BYTE),
  STANDARD_VALUE  NUMBER(10,2)                  NOT NULL,
  HIGH_VALUE      NUMBER(10,2)                  NOT NULL,
  MIN_VALUE       NUMBER(10,2)                  NOT NULL,
  REMARKS         VARCHAR2(200 BYTE),
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_BY      VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_DATE    DATE                          NOT NULL,
  DELETED_FLAG    CHAR(1 BYTE),
  SYN_ROWID       VARCHAR2(18 BYTE),
  MODIFY_DATE     DATE,
  MODIFY_BY       VARCHAR2(30 BYTE),
  SERIAL_NO       VARCHAR2(10 BYTE),
  ROLL1           VARCHAR2(20 BYTE),
  ROLL2           VARCHAR2(20 BYTE),
  ROLL3           VARCHAR2(20 BYTE)
)
TABLESPACE BHPL8182
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX BHPL8182.PK_QP_SETUP ON BHPL8182.IP_ITEM_QC_SETUP
(COMPANY_CODE, ITEM_CODE, QC_CODE)
NOLOGGING
TABLESPACE BHPL8182
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE BHPL8182.IP_ITEM_QC_SETUP ADD (
  CONSTRAINT CK_QP_SETUP_DELETED_FLAG
  CHECK (DELETED_FLAG IN ('Y','N'))
  ENABLE NOVALIDATE
,  CONSTRAINT PK_QP_SETUP
  PRIMARY KEY
  (COMPANY_CODE, ITEM_CODE, QC_CODE)
  USING INDEX BHPL8182.PK_QP_SETUP
  ENABLE VALIDATE);





select * from ip_item_qc_setup;
select * from IP_INTEGRATION_SETUP  ;
select * from QC_PARAMETER_TRANSACTION;
select * from QC_MASTER_TRANSACTION;
select * from IP_ITEM_QC_PARAMETER_SETUP ;
select * from ip_item_master_setup;
select * from IP_ITEM_SPEC_SETUP;
select * from  ip_supplier_setup;
select * from   ip_purchase_mrr;
select * from   IP_GATE_ENTRY_DETAIL;
select * from   IP_GATE_ENTRY;
select * from form_setup;
select * from batch_transaction;


ALTER TABLE QC_PARAMETER_TRANSACTION
ADD CONSTRAINT PK_PARAMETER_TRANSACTION
PRIMARY KEY (TRANSACTION_NO);

ALTER TABLE IP_ITEM_DAILY_WASTAGE
ADD CONSTRAINT FK_IP_ITEM_DAILY_WASTAGE
FOREIGN KEY (IP_ITEM_DAILY_WASTAGE_NO)
REFERENCES QC_PARAMETER_TRANSACTION (TRANSACTION_NO);


SELECT FORM_CODE,FORM_EDESC,MASTER_FORM_CODE,PRE_FORM_CODE,MODULE_CODE,GROUP_SKU_FLAG,START_ID_FLAG,ID_GENERATION_FLAG,CUSTOM_SUFFIX_TEXT,START_DATE,
            LAST_DATE,REF_COLUMN_NAME,PRINT_REPORT_FLAG,PRIMARY_MANUAL_FLAG,COMPANY_CODE,CREATED_DATE
            ,DELETED_FLAG,REFERENCE_FLAG,FORM_ACTION_FLAG,MODIFY_DATE FROM FORM_SETUP WHERE 
            FORM_CODE='496' AND
            COMPANY_CODE=01  
            ORDER BY TO_NUMBER(FORM_CODE) ASC;
            
            
select IIMS.item_edesc AS RAWMATERIAL
, CASE WHEN IGE.INWARD_TYPE IN ('Referencial Outward' )THEN (SELECT CUSTOMER_EDESC 
FROM SA_CUSTOMER_SETUP WHERE CUSTOMER_CODE = IGE.SUPPLIER_CODE AND COMPANY_CODE = IGE.COMPANY_CODE )
ELSE  (SELECT SUPPLIER_EDESC FROM IP_SUPPLIER_SETUP WHERE SUPPLIER_CODE = IGE.SUPPLIER_CODE 
AND COMPANY_CODE = IGE.COMPANY_CODE ) END  SUPPLIER_EDESC,BTN.BATCH_NO,IISS.GSM,IISS.SIZE_WIDTH,IISS.STRENGTH
,IISS.THICKNESS
,IISS.GSM AS ACTUAL_GSM,IISS.SIZE_WIDTH AS ACTUAL_SIZE_WIDTH,IISS.STRENGTH AS ACTUAL_STRENGTH
,IISS.THICKNESS AS ACTUAL_THICKNESS,IISS.REMARKS
from ip_item_master_setup IIMS
LEFT JOIN IP_GATE_ENTRY_DETAIL IGED ON IGED.item_code = IIMS.item_code
LEFT JOIN IP_GATE_ENTRY  IGE ON IGE.GATE_NO =  IGED.GATE_NO
LEFT JOIN BATCH_TRANSACTION BTN ON BTN.item_code = IIMS.item_code
LEFT JOIN  IP_ITEM_SPEC_SETUP IISS ON IISS.item_code = IIMS.item_code


CREATE TABLE BHPL8182.IP_ITEM_QC_PARAMETER_DETAILS
(
  SERIAL_NO      VARCHAR2(10 BYTE)              NOT NULL,
  PARAM_CODE     VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  PARAMETERS     VARCHAR2(100 BYTE),
  TARGET         VARCHAR2(120 BYTE),
  TOLERENCE      VARCHAR2(120 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE),
  SPECIFICATION  VARCHAR2(100 BYTE)
)


ALTER TABLE GLOBAL_PRODUCTS_TRANSACTION 
ADD ISUNLOAD CHAR(1 BYTE);

ALTER TABLE GLOBAL_PRODUCTS_TRANSACTION 
ADD ISPROTEIN CHAR(1 BYTE);

ALTER TABLE GLOBAL_PRODUCTS_TRANSACTION 
ADD ISPT CHAR(1 BYTE);

ALTER TABLE GLOBAL_PRODUCTS_TRANSACTION 
ADD ISOUT CHAR(1 BYTE);


DROP TABLE IP_ITEM_QC_PARAMETER_MASTER CASCADE CONSTRAINTS;
CREATE TABLE IP_ITEM_QC_PARAMETER_MASTER
(
  PARAM_CODE     VARCHAR2(30 BYTE)               NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE),
  SYN_ROWID     VARCHAR2(18 BYTE),
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE)
)



CREATE TABLE IP_ITEM_QC_PARAMETER_DETAILS
(
  SERIAL_NO     VARCHAR2(10 BYTE)               NOT NULL,
  PARAM_CODE     VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE     VARCHAR2(30 BYTE)               NOT NULL,
  PARAMETERS    VARCHAR2(100 BYTE),
  TARGET        VARCHAR2(120 BYTE),
  TOLERENCE     VARCHAR2(120 BYTE),
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE),
  SYN_ROWID     VARCHAR2(18 BYTE),
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE)
)

CREATE TABLE BHPL8182.ONSITEINSPECTIONDETAILS
(
  SERIAL_NO      VARCHAR2(10 BYTE)              NOT NULL,
  PARAM_CODE     VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  INSPECTION_NO  VARCHAR2(30 BYTE)              NOT NULL,
  TARGET         VARCHAR2(30 BYTE),
  TOLERENCE      VARCHAR2(30 BYTE),
  RESULTS        VARCHAR2(30 BYTE),
  VARIANCE       VARCHAR2(30 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE)
)

DROP TABLE OnSiteInspection CASCADE CONSTRAINTS;
CREATE TABLE OnSiteInspection
(

Inspection_No VARCHAR2(30 BYTE)               NOT NULL,
Plant_Id VARCHAR2(30 BYTE)               NOT NULL,
Product_Id VARCHAR2(30 BYTE)               NOT NULL,
Batch_No VARCHAR2(30 BYTE)               ,
Shift VARCHAR2(30 BYTE)               NOT NULL,
Reference_No VARCHAR2(20 BYTE)               NOT NULL,
COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE),
  SYN_ROWID     VARCHAR2(18 BYTE),
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE)
)

CREATE TABLE BHPL8182.INTERNALINSPECTION
(
  SERIAL_NO      VARCHAR2(10 BYTE)              NOT NULL,
  PARAM_CODE     VARCHAR2(30 BYTE)              NOT NULL,
  INSPECTION_NO  VARCHAR2(30 BYTE)              NOT NULL,
  SPECIFICATION  VARCHAR2(30 BYTE),
  UNIT           VARCHAR2(30 BYTE),
  TARGET         VARCHAR2(30 BYTE),
  TOLERENCE      VARCHAR2(30 BYTE),
  RESULTS        VARCHAR2(30 BYTE),
  VARIANCE       VARCHAR2(30 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE),
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  PARAMETER_ID   VARCHAR2(10 BYTE)              NOT NULL
)

ALTER TABLE IP_ITEM_QC_PARAMETER_DETAILS
ADD (SPECIFICATION VARCHAR2(100 BYTE));

ALTER TABLE INTERNALINSPECTION
ADD (
    ITEM_CODE     VARCHAR2(30 BYTE) NOT NULL,
    PARAMETER_ID  VARCHAR2(10 BYTE) NOT NULL
);
commit;



CREATE TABLE INSPECTION_PARAMETERS
(
  INSPECTION_PARAM_NO  VARCHAR2(30 BYTE)              NOT NULL,
  PARAMETERS     VARCHAR2(30 BYTE)              NOT NULL
)


CREATE TABLE INSPECTION_PARAM_DETAILS
(
  INS_PARAM_DETAIL_NO  VARCHAR2(30 BYTE)  NOT NULL,
  PARAMETER_ID                VARCHAR2(10 BYTE)  NOT NULL,
  COMPANY_CODE                VARCHAR2(30 BYTE)  NOT NULL,
  BRANCH_CODE                 VARCHAR2(30 BYTE)  NOT NULL,
  CREATED_BY                  VARCHAR2(30 BYTE)  NOT NULL,
  CREATED_DATE                DATE               NOT NULL,
  DELETED_FLAG                CHAR(1 BYTE),
  SYN_ROWID                   VARCHAR2(18 BYTE),
  SESSION_ROWID               VARCHAR2(18 BYTE),
  MODIFY_DATE                 DATE,
  MODIFY_BY                   VARCHAR2(30 BYTE),
  CONSTRAINT PK_INSPECTION_PARAM_DETAILS PRIMARY KEY (INS_PARAM_DETAIL_NO)
);

CREATE TABLE PARAM_ITEM_MAP
(
  PARAM_ITEM_NO  VARCHAR2(30 BYTE)       NOT NULL,
  SERIAL_NO             NUMBER(5)               NOT NULL,
  ITEM_NAME     VARCHAR2(100 BYTE)              NOT NULL,
  PARAM_NO     VARCHAR2(10 BYTE)              NOT NULL,
  COMPANY_CODE                VARCHAR2(30 BYTE)  NOT NULL,
  BRANCH_CODE                 VARCHAR2(30 BYTE)  NOT NULL,
  CREATED_BY                  VARCHAR2(30 BYTE)  NOT NULL,
  CREATED_DATE                DATE               NOT NULL,
  DELETED_FLAG                CHAR(1 BYTE),
  MODIFY_DATE                 DATE,
  MODIFY_BY                   VARCHAR2(30 BYTE)
)


CREATE TABLE HANDOVER_INSPECTION
(
  HANDOVER_INSPECTION_NO  VARCHAR2(20 BYTE) NOT NULL,
  TIME_PERIOD                 VARCHAR2(30 BYTE) NOT NULL,
  ITEM_CODE                   VARCHAR2(30 BYTE) NOT NULL,
  BATCH_NO                    VARCHAR2(20 BYTE),
  LOOSE_PRODUCT_SAMPLE        VARCHAR2(30 BYTE),
  LOOSE_PRODUCT_DEFECT        VARCHAR2(30 BYTE),
  UNSEALED_PACKET_SAMPLE      VARCHAR2(30 BYTE),
  UNSEALED_PACKET_DEFECT      VARCHAR2(30 BYTE),
  SEALED_PACKET_SAMPLE        VARCHAR2(30 BYTE),
  SEALED_PACKET_DEFECT        VARCHAR2(30 BYTE),
  BAG_SAMPLE                  VARCHAR2(30 BYTE),
  BAG_DEFECT                  VARCHAR2(30 BYTE),
  WRAPPER_SAMPLE              VARCHAR2(30 BYTE),
  WRAPPER_DEFECT              VARCHAR2(30 BYTE),
  REMARKS                     VARCHAR2(200 BYTE),
  COMPANY_CODE                VARCHAR2(30 BYTE) NOT NULL,
  BRANCH_CODE                 VARCHAR2(30 BYTE) NOT NULL,
  CREATED_BY                  VARCHAR2(30 BYTE) NOT NULL,
  CREATED_DATE                DATE              NOT NULL,
  DELETED_FLAG                CHAR(1 BYTE),
  MODIFY_DATE                 DATE,
  MODIFY_BY                   VARCHAR2(30 BYTE),
  SERIAL_NO                   VARCHAR2(10 BYTE),
  FORM_CODE                   VARCHAR2(10 BYTE) NOT NULL
)

COMMIT;


ALTER TABLE QC_PARAMETER_TRANSACTION
ADD (
  CUSTOMER_INVOICE_NO  VARCHAR2(20 BYTE),
  CUSTOMER_CODE        VARCHAR2(30 BYTE),
  TRANSPORT_DETAIL     VARCHAR2(100 BYTE),
  DRIVER_NAME          VARCHAR2(50 BYTE),
  DRIVER_CONTACT_NO    VARCHAR2(20 BYTE),
  VEHICLE_NO           VARCHAR2(30 BYTE)
);

commit;

ALTER TABLE IP_ITEM_DAILY_WASTAGE
DROP COLUMN DAY;

ALTER TABLE IP_ITEM_DAILY_WASTAGE
ADD (
    UNIT VARCHAR2(50),
    QTY NUMBER(18,2)
);

commit;


ALTER TABLE IP_ITEM_SPEC_SETUP 
ADD (STRENGTH_MD VARCHAR2(20 BYTE));

COMMIT;

ALTER TABLE IP_ITEM_QC_TESTING 
ADD (STRENGTH_MD VARCHAR2(20 BYTE));

ALTER TABLE IP_ITEM_QC_TESTING 
ADD (ACTUAL_STRENGTH_MD VARCHAR2(20 BYTE));

ALTER TABLE IP_ITEM_QC_TESTING 
ADD (ROLL_NO VARCHAR2(20 BYTE));

COMMIT;

IP_ITEM_SPEC_SETUP table for GSM,THICKNESS etc.

ALTER TABLE IP_ITEM_QC_SETUP
ADD IP_ITEM_QC_SETUP_NO VARCHAR2(20 BYTE) NOT NULL;
COMMIT;

CREATE TABLE FINISHED_PARAM_DETAILS
(
  FINISH_PARAM_DETAIL_NO  VARCHAR2(30 BYTE)        NOT NULL,
  PARAMETER_ID         VARCHAR2(10 BYTE)        NOT NULL,
  COMPANY_CODE         VARCHAR2(30 BYTE)        NOT NULL,
  BRANCH_CODE          VARCHAR2(30 BYTE)        NOT NULL,
  CREATED_BY           VARCHAR2(30 BYTE)        NOT NULL,
  CREATED_DATE         DATE                     NOT NULL,
  DELETED_FLAG         CHAR(1 BYTE),
  SYN_ROWID            VARCHAR2(18 BYTE),
  SESSION_ROWID        VARCHAR2(18 BYTE),
  MODIFY_DATE          DATE,
  MODIFY_BY            VARCHAR2(30 BYTE)
)

CREATE TABLE FINISH_ITEM_MAP
(
  FINISH_ITEM_NO  VARCHAR2(30 BYTE)              NOT NULL,
  SERIAL_NO      NUMBER(5)                      NOT NULL,
  ITEM_NAME      VARCHAR2(100 BYTE)             NOT NULL,
  PARAM_NO       VARCHAR2(10 BYTE)              NOT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE)
)

COMMIT;

CREATE TABLE FINISHED_INSPECTION_PARAMETERS
(
  FINISHED_PARAM_NO  VARCHAR2(30 BYTE)              NOT NULL,
  PARAMETERS     VARCHAR2(30 BYTE)              NOT NULL
)


CREATE TABLE FINISH_GOODS_INSP
(
  FINISH_GOODS_INSP_NO     VARCHAR2(20 BYTE)    NOT NULL,
  ITEM_CODE                VARCHAR2(30 BYTE)    NOT NULL,
  PACK_CONDITION           VARCHAR2(50 BYTE),
  PACK_COND_REMARKS        VARCHAR2(100 BYTE),
  LABEL_ACCURACY           VARCHAR2(50 BYTE),
  LABEL_ACC_REMARKS        VARCHAR2(100 BYTE),
  PRODUCT_APPEARANCE       VARCHAR2(50 BYTE),
  PRODUCT_APP_REMARKS      VARCHAR2(100 BYTE),
  DIMENSIONS               VARCHAR2(50 BYTE),
  DIMENSIONS_REMARKS       VARCHAR2(100 BYTE),
  COMPLIANCE_CERTIFICATES  VARCHAR2(50 BYTE),
  COMP_CERT_REMARKS        VARCHAR2(100 BYTE),
  VENDOR_TEST              VARCHAR2(50 BYTE),
  VENDOR_TEST_REMARKS      VARCHAR2(100 BYTE),
  SAMPLING_METHOD          VARCHAR2(50 BYTE),
  SAMP_METHOD_REMARKS      VARCHAR2(100 BYTE),
  SAMPLE_SIZE              VARCHAR2(50 BYTE),
  SAMP_SIZE_REMARKS        VARCHAR2(100 BYTE),
  NUMBER_PASSED            VARCHAR2(50 BYTE),
  NUMBER_PASSED_REMARKS    VARCHAR2(100 BYTE),
  DEFECT_TYPE              VARCHAR2(50 BYTE),
  DEFECT_TYPE_REMARKS      VARCHAR2(100 BYTE),
  ACTION_TAKEN             VARCHAR2(50 BYTE),
  ACTION_TAKEN_REMARKS     VARCHAR2(100 BYTE),
  REMARKS                  VARCHAR2(50 BYTE),
  FINAL_REMARKS            VARCHAR2(100 BYTE),
  SUPPLIER_CODE            VARCHAR2(30 BYTE),
  GRN_NO                   VARCHAR2(30 BYTE),
  MFG_DATE                 DATE,
  EXP_DATE                 DATE,
  QUANTITY                 VARCHAR2(20 BYTE),
  FORM_CODE                 VARCHAR2(10 BYTE)   NOT NULL,
  BRANCH_CODE               VARCHAR2(30 BYTE)   NOT NULL,
  COMPANY_CODE             VARCHAR2(30 BYTE)    NOT NULL,
  CREATED_BY               VARCHAR2(30 BYTE)    NOT NULL,
  CREATED_DATE             DATE                 NOT NULL,
  DELETED_FLAG             CHAR(1 BYTE),
  SYN_ROWID                VARCHAR2(18 BYTE),
  MODIFY_DATE              DATE,
  MODIFY_BY                VARCHAR2(30 BYTE),
  SERIAL_NO                VARCHAR2(10 BYTE)
)

/*sashi*/