
CREATE TABLE QC_PARAMETER_TRANSACTION
(
  TRANSACTION_NO        VARCHAR2(20 BYTE)       NOT NULL,
  REFERENCE_NO          VARCHAR2(20 BYTE)       NOT NULL,
  ITEM_CODE             VARCHAR2(30 BYTE)       NOT NULL,
  SERIAL_NO             NUMBER(5)               NOT NULL,
  QC_CODE               VARCHAR2(20 BYTE)       NOT NULL,
  STD_VALUE_PERCENT     NUMBER(14,4),
  ACTUAL_VALUE_PERCENT  NUMBER(14,4),
  REMARKS               VARCHAR2(200 BYTE),
  FORM_CODE             VARCHAR2(10 BYTE)       NOT NULL,
  COMPANY_CODE          VARCHAR2(30 BYTE)       NOT NULL,
  BRANCH_CODE           VARCHAR2(30 BYTE)       NOT NULL,
  CREATED_BY            VARCHAR2(30 BYTE)       NOT NULL,
  CREATED_DATE          DATE                    NOT NULL,
  DELETED_FLAG          CHAR(1 BYTE),
  SYN_ROWID             VARCHAR2(18 BYTE),
  SESSION_ROWID         VARCHAR2(18 BYTE),
  MODIFY_DATE           DATE,
  MODIFY_BY             VARCHAR2(30 BYTE),
  CHECKED_BY            VARCHAR2(30 BYTE),
  AUTHORISED_BY         VARCHAR2(30 BYTE),
  BATCH_NO              VARCHAR2(20 BYTE),
  SHIFT                 VARCHAR2(30 BYTE),
  CUSTOMER_INVOICE_NO   VARCHAR2(20 BYTE),
  CUSTOMER_CODE         VARCHAR2(100 BYTE),
  TRANSPORT_DETAIL      VARCHAR2(100 BYTE),
  DRIVER_NAME           VARCHAR2(50 BYTE),
  DRIVER_CONTACT_NO     VARCHAR2(20 BYTE),
  VEHICLE_NO            VARCHAR2(30 BYTE),
  DISPATCH_PERSON       VARCHAR2(80 BYTE),
  QC_INSPECTOR          VARCHAR2(80 BYTE),
  CUSTOMER_NAME         VARCHAR2(100 BYTE),
  GRN_NO                VARCHAR2(30 BYTE),
  MFG_DATE              DATE,
  EXP_DATE              DATE,
  QUANTITY              VARCHAR2(20 BYTE),
  VENDOR_NAME           VARCHAR2(100 BYTE),
  RECEIPT_DATE          DATE,
  MANUAL_NO             VARCHAR2(80 BYTE),
  UNIT                  VARCHAR2(20 BYTE),
  QC_DATE               DATE,
  LC_NO                 VARCHAR2(100 BYTE),
  GRN_DATE              DATE,
  NAME                  VARCHAR2(100 BYTE),
  OVERALL_REMARKS       VARCHAR2(200 BYTE),
  CHECKED_DATE          DATE,
  AUTHORISED_DATE       DATE,
  POSTED_DATE           DATE,
  POSTED_BY             VARCHAR2(30 BYTE),
  POSTED_FLAG           CHAR(1 BYTE)
)


--------------------------------------------------------------------------

CREATE TABLE IP_ITEM_DAILY_WASTAGE
(
  IP_ITEM_DAILY_WASTAGE_NO  VARCHAR2(20 BYTE)   NOT NULL,
  PARAM_CODE                VARCHAR2(30 BYTE)   NOT NULL,
  ITEM_CODE                 VARCHAR2(30 BYTE)   NOT NULL,
  COMPANY_CODE              VARCHAR2(30 BYTE)   NOT NULL,
  BRANCH_CODE               VARCHAR2(30 BYTE)   NOT NULL,
  CREATED_BY                VARCHAR2(30 BYTE)   NOT NULL,
  CREATED_DATE              DATE                NOT NULL,
  DELETED_FLAG              CHAR(1 BYTE),
  MODIFY_DATE               DATE,
  MODIFY_BY                 VARCHAR2(30 BYTE),
  SERIAL_NO                 VARCHAR2(10 BYTE),
  FORM_CODE                 VARCHAR2(10 BYTE)   NOT NULL,
  UNIT                      VARCHAR2(50 BYTE),
  QTY                       NUMBER(18,2)
)

-----------------------------------------------------------------------------

CREATE TABLE PRODUCT_PARAM_MAP
(
  INSPECTION_NO  VARCHAR2(30 BYTE)              NOT NULL,
  PRODUCT_ID     VARCHAR2(30 BYTE)              NOT NULL
)

-----------------------------------------------------------------------------

CREATE TABLE FINISHED_INSPECTION_PARAMETERS
(
  FINISHED_PARAM_NO  VARCHAR2(30 BYTE)          NOT NULL,
  PARAMETERS         VARCHAR2(30 BYTE)          NOT NULL
)

-------------------------------------------------------------------------------

CREATE TABLE FINISH_ITEM_MAP
(
  FINISH_ITEM_NO  VARCHAR2(30 BYTE)             NOT NULL,
  SERIAL_NO       NUMBER(5)                     NOT NULL,
  ITEM_NAME       VARCHAR2(100 BYTE)            NOT NULL,
  COLUMN_HEADER   VARCHAR2(100 BYTE)            NOT NULL,
  PARAM_NO        VARCHAR2(10 BYTE)             NOT NULL,
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  BRANCH_CODE     VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_BY      VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_DATE    DATE                          NOT NULL,
  DELETED_FLAG    CHAR(1 BYTE),
  MODIFY_DATE     DATE,
  MODIFY_BY       VARCHAR2(30 BYTE)
)

------------------------------------------------------------------------------

CREATE TABLE IP_ITEM_QC_TESTING
(
  ITEM_CODE              VARCHAR2(30 BYTE)      NOT NULL,
  COMPANY_CODE           VARCHAR2(30 BYTE)      NOT NULL,
  BRANCH_CODE            VARCHAR2(30 BYTE)      NOT NULL,
  CREATED_BY             VARCHAR2(30 BYTE)      NOT NULL,
  CREATED_DATE           DATE                   NOT NULL,
  DELETED_FLAG           CHAR(1 BYTE),
  MODIFY_DATE            DATE,
  MODIFY_BY              VARCHAR2(30 BYTE),
  SERIAL_NO              VARCHAR2(10 BYTE),
  SUPPLIER_CODE          VARCHAR2(30 BYTE),
  FORM_CODE              VARCHAR2(10 BYTE)      NOT NULL,
  BATCH_NO               VARCHAR2(20 BYTE),
  GSM                    VARCHAR2(20 BYTE),
  WIDTH                  VARCHAR2(20 BYTE),
  STRENGTH               VARCHAR2(20 BYTE),
  THICKNESS              VARCHAR2(20 BYTE),
  ACTUAL_GSM             VARCHAR2(20 BYTE),
  ACTUAL_WIDTH           VARCHAR2(20 BYTE),
  ACTUAL_STRENGTH        VARCHAR2(20 BYTE),
  ACTUAL_THICKNESS       VARCHAR2(20 BYTE),
  REMARKS                VARCHAR2(200 BYTE),
  STRENGTH_MD            VARCHAR2(20 BYTE),
  ACTUAL_STRENGTH_MD     VARCHAR2(20 BYTE),
  ROLL_NO                VARCHAR2(20 BYTE),
  IP_ITEM_QC_TESTING_NO  VARCHAR2(20 BYTE)      NOT NULL
)

-------------------------------------------------------------------------------------------------------------

CREATE TABLE ONSITEINSPECTIONDETAILS
(
  SERIAL_NO      VARCHAR2(10 BYTE)              NOT NULL,
  PARAM_CODE     VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  INSPECTION_NO  VARCHAR2(30 BYTE)              NOT NULL,
  TARGET         VARCHAR2(30 BYTE),
  TOLERENCE      VARCHAR2(30 BYTE),
  RESULTS        VARCHAR2(30 BYTE),
  VARIANCE       VARCHAR2(30 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE)
)

------------------------------------------------------------------------------------------------------------




CREATE TABLE FINISH_GOODS_INSPECTION
(
  FINISH_GOODS_INSP_NO     VARCHAR2(20 BYTE)    NOT NULL,
  ITEM_CODE                VARCHAR2(30 BYTE)    NOT NULL,
  PACK_CONDITION           CHAR(1 BYTE),
  PACK_COND_REMARKS        VARCHAR2(100 BYTE),
  LABEL_ACCURACY           CHAR(1 BYTE),
  LABEL_ACC_REMARKS        VARCHAR2(100 BYTE),
  PRODUCT_APPEARANCE       CHAR(1 BYTE),
  PRODUCT_APP_REMARKS      VARCHAR2(100 BYTE),
  DIMENSIONS               CHAR(1 BYTE),
  DIMENSIONS_REMARKS       VARCHAR2(100 BYTE),
  COMPLIANCE_CERTIFICATES  CHAR(1 BYTE),
  COMP_CERT_REMARKS        VARCHAR2(100 BYTE),
  VENDOR_TEST              CHAR(1 BYTE),
  VENDOR_TEST_REMARKS      VARCHAR2(100 BYTE),
  SAMPLING_METHOD          VARCHAR2(50 BYTE),
  SAMP_METHOD_REMARKS      VARCHAR2(100 BYTE),
  SAMPLE_SIZE              VARCHAR2(50 BYTE),
  SAMP_SIZE_REMARKS        VARCHAR2(100 BYTE),
  NUMBER_PASSED            CHAR(1 BYTE),
  NUMBER_PASSED_REMARKS    VARCHAR2(100 BYTE),
  DEFECT_TYPE              VARCHAR2(50 BYTE),
  DEFECT_TYPE_REMARKS      VARCHAR2(100 BYTE),
  ACTION_TAKEN             VARCHAR2(50 BYTE),
  ACTION_TAKEN_REMARKS     VARCHAR2(100 BYTE),
  REMARKS                  VARCHAR2(50 BYTE),
  FINAL_REMARKS            VARCHAR2(100 BYTE),
  SUPPLIER_CODE            VARCHAR2(30 BYTE),
  FORM_CODE                VARCHAR2(10 BYTE)    NOT NULL,
  BRANCH_CODE              VARCHAR2(30 BYTE)    NOT NULL,
  COMPANY_CODE             VARCHAR2(30 BYTE)    NOT NULL,
  CREATED_BY               VARCHAR2(30 BYTE)    NOT NULL,
  CREATED_DATE             DATE                 NOT NULL,
  DELETED_FLAG             CHAR(1 BYTE),
  SYN_ROWID                VARCHAR2(18 BYTE),
  MODIFY_DATE              DATE,
  MODIFY_BY                VARCHAR2(30 BYTE),
  SERIAL_NO                VARCHAR2(10 BYTE)
)

------------------------------------------------------------------------------------------------

CREATE TABLE FINISHED_PARAM_DETAILS
(
  FINISH_PARAM_DETAIL_NO  VARCHAR2(30 BYTE)     NOT NULL,
  PARAMETER_ID            VARCHAR2(10 BYTE)     NOT NULL,
  COMPANY_CODE            VARCHAR2(30 BYTE)     NOT NULL,
  BRANCH_CODE             VARCHAR2(30 BYTE)     NOT NULL,
  CREATED_BY              VARCHAR2(30 BYTE)     NOT NULL,
  CREATED_DATE            DATE                  NOT NULL,
  DELETED_FLAG            CHAR(1 BYTE),
  SYN_ROWID               VARCHAR2(18 BYTE),
  SESSION_ROWID           VARCHAR2(18 BYTE),
  MODIFY_DATE             DATE,
  MODIFY_BY               VARCHAR2(30 BYTE)
)

--------------------------------------------------------------------------------------------------

CREATE TABLE HANDOVER_INSPECTION
(
  HANDOVER_INSPECTION_NO  VARCHAR2(20 BYTE)     NOT NULL,
  TIME_PERIOD             VARCHAR2(30 BYTE)     NOT NULL,
  ITEM_CODE               VARCHAR2(30 BYTE)     NOT NULL,
  BATCH_NO                VARCHAR2(20 BYTE),
  LOOSE_PRODUCT_SAMPLE    VARCHAR2(30 BYTE),
  LOOSE_PRODUCT_DEFECT    VARCHAR2(30 BYTE),
  UNSEALED_PACKET_SAMPLE  VARCHAR2(30 BYTE),
  UNSEALED_PACKET_DEFECT  VARCHAR2(30 BYTE),
  SEALED_PACKET_SAMPLE    VARCHAR2(30 BYTE),
  SEALED_PACKET_DEFECT    VARCHAR2(30 BYTE),
  BAG_SAMPLE              VARCHAR2(30 BYTE),
  BAG_DEFECT              VARCHAR2(30 BYTE),
  WRAPPER_SAMPLE          VARCHAR2(30 BYTE),
  WRAPPER_DEFECT          VARCHAR2(30 BYTE),
  REMARKS                 VARCHAR2(200 BYTE),
  COMPANY_CODE            VARCHAR2(30 BYTE)     NOT NULL,
  BRANCH_CODE             VARCHAR2(30 BYTE)     NOT NULL,
  CREATED_BY              VARCHAR2(30 BYTE)     NOT NULL,
  CREATED_DATE            DATE                  NOT NULL,
  DELETED_FLAG            CHAR(1 BYTE),
  MODIFY_DATE             DATE,
  MODIFY_BY               VARCHAR2(30 BYTE),
  SERIAL_NO               VARCHAR2(10 BYTE),
  FORM_CODE               VARCHAR2(10 BYTE)     NOT NULL,
  PRODUCT_TYPE            VARCHAR2(30 BYTE)
)

------------------------------------------------------------------------------------------------

CREATE TABLE INTERNALINSPECTION
(
  SERIAL_NO      VARCHAR2(10 BYTE)              NOT NULL,
  INSPECTION_NO  VARCHAR2(30 BYTE)              NOT NULL,
  PRODUCT_ID     VARCHAR2(20 BYTE)              NOT NULL,
  SPECIFICATION  VARCHAR2(30 BYTE),
  UNIT           VARCHAR2(30 BYTE),
  TARGET         VARCHAR2(30 BYTE),
  TOLERENCE      VARCHAR2(30 BYTE),
  RESULTS        VARCHAR2(30 BYTE),
  VARIANCE       VARCHAR2(30 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE)
)

------------------------------------------------------------------------------------------------

CREATE TABLE INTERNAL_PRODUCT_MAP
(
  INSPECTION_NO  VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  QUANTITY       VARCHAR2(30 BYTE)              NOT NULL
)

-----------------------------------------------------------------------------------------------


CREATE TABLE IP_PRODUCT_MASTER
(
  PRODUCT_ID    VARCHAR2(30 BYTE)               NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE),
  SYN_ROWID     VARCHAR2(18 BYTE),
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE),
  PRODUCT       VARCHAR2(120 BYTE)
)

---------------------------------------------------------------------------------------------

CREATE TABLE PRODUCT_ITEMS_MAP
(
  PRODUCT_ID  VARCHAR2(30 BYTE)                 NOT NULL,
  ITEM_ID     VARCHAR2(30 BYTE)                 NOT NULL
)

----------------------------------------------------------------------------------------------


CREATE TABLE IP_PRODUCT_PARAMETER_DETAILS
(
  SERIAL_NO      VARCHAR2(10 BYTE)              NOT NULL,
  PRODUCT_ID     VARCHAR2(30 BYTE)              NOT NULL,
  PARAMETERS     VARCHAR2(100 BYTE),
  TARGET         VARCHAR2(120 BYTE),
  TOLERENCE      VARCHAR2(120 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE),
  SPECIFICATION  VARCHAR2(100 BYTE),
  UNIT           VARCHAR2(20 BYTE)
)

------------------------------------------------------------------------------------------------

CREATE TABLE IP_ITEM_QC_SETUP
(
  ITEM_CODE            VARCHAR2(30 BYTE)        NOT NULL,
  QC_CODE              VARCHAR2(10 BYTE)        NOT NULL,
  QC_EDESC             VARCHAR2(100 BYTE)       NOT NULL,
  QC_NDESC             VARCHAR2(100 BYTE),
  STANDARD_VALUE       NUMBER(10,2)             NOT NULL,
  HIGH_VALUE           NUMBER(10,2)             NOT NULL,
  MIN_VALUE            NUMBER(10,2)             NOT NULL,
  REMARKS              VARCHAR2(200 BYTE),
  COMPANY_CODE         VARCHAR2(30 BYTE)        NOT NULL,
  CREATED_BY           VARCHAR2(30 BYTE)        NOT NULL,
  CREATED_DATE         DATE                     NOT NULL,
  DELETED_FLAG         CHAR(1 BYTE),
  SYN_ROWID            VARCHAR2(18 BYTE),
  MODIFY_DATE          DATE,
  MODIFY_BY            VARCHAR2(30 BYTE),
  SERIAL_NO            VARCHAR2(10 BYTE),
  ROLL1                VARCHAR2(20 BYTE),
  ROLL2                VARCHAR2(20 BYTE),
  ROLL3                VARCHAR2(20 BYTE),
  IP_ITEM_QC_SETUP_NO  VARCHAR2(20 BYTE)        NOT NULL,
  SPECIFICATION        VARCHAR2(100 BYTE)
)

-------------------------------------------------------------------------------------------------

CREATE TABLE INSPECTION_PARAM_DETAILS
(
  INS_PARAM_DETAIL_NO  VARCHAR2(30 BYTE)        NOT NULL,
  PARAMETER_ID         VARCHAR2(10 BYTE)        NOT NULL,
  COMPANY_CODE         VARCHAR2(30 BYTE)        NOT NULL,
  BRANCH_CODE          VARCHAR2(30 BYTE)        NOT NULL,
  CREATED_BY           VARCHAR2(30 BYTE)        NOT NULL,
  CREATED_DATE         DATE                     NOT NULL,
  DELETED_FLAG         CHAR(1 BYTE),
  SYN_ROWID            VARCHAR2(18 BYTE),
  SESSION_ROWID        VARCHAR2(18 BYTE),
  MODIFY_DATE          DATE,
  MODIFY_BY            VARCHAR2(30 BYTE)
)

--------------------------------------------------------------------------------------------------

ALTER TABLE IP_ITEM_SPEC_SETUP
ADD (
    ROLLDIAMETER            VARCHAR2(20 BYTE),
    PH                      VARCHAR2(20 BYTE),
    UNPLEASANT_SMELL_ODOUR  VARCHAR2(20 BYTE),
    DUST_DIRT               VARCHAR2(20 BYTE),
    DAMAGING_MATERIAL       VARCHAR2(20 BYTE),
    CORE_DAMAGING           VARCHAR2(20 BYTE),
    TENSILE_CD              VARCHAR2(20 BYTE),
    TENSILE_MD              VARCHAR2(20 BYTE),
    VISUAL_INSPECTION       VARCHAR2(20 BYTE),
    STRENGTH                VARCHAR2(20 BYTE),
    STRENGTH_MD             VARCHAR2(20 BYTE)
);



<!--CREATE TABLE IP_ITEM_SPEC_SETUP
(
  ITEM_CODE               VARCHAR2(30 BYTE)     NOT NULL,
  PART_NUMBER             VARCHAR2(255 BYTE),
  BRAND_NAME              VARCHAR2(100 BYTE),
  ITEM_SPECIFICATION      VARCHAR2(100 BYTE),
  ITEM_APPLY_ON           VARCHAR2(100 BYTE),
  INTERFACE               VARCHAR2(20 BYTE),
  TYPE                    VARCHAR2(20 BYTE),
  LAMINATION              VARCHAR2(20 BYTE),
  ITEM_SIZE               VARCHAR2(20 BYTE),
  THICKNESS               VARCHAR2(20 BYTE),
  COLOR                   VARCHAR2(50 BYTE),
  GRADE                   VARCHAR2(20 BYTE),
  REMARKS                 VARCHAR2(200 BYTE),
  COMPANY_CODE            VARCHAR2(30 BYTE)     NOT NULL,
  CREATED_BY              VARCHAR2(30 BYTE)     NOT NULL,
  CREATED_DATE            DATE                  NOT NULL,
  DELETED_FLAG            CHAR(1 BYTE),
  MODIFY_DATE             DATE,
  SYN_ROWID               VARCHAR2(18 BYTE),
  MODIFY_BY               VARCHAR2(30 BYTE),
  GSM                     VARCHAR2(20 BYTE),
  SIZE_LENGHT             NUMBER,
  SIZE_WIDTH              NUMBER,
  SPEC_COMPULSORY_FLAG    CHAR(1 BYTE),
  ROLLDIAMETER            VARCHAR2(20 BYTE),
  PH                      VARCHAR2(20 BYTE),
  UNPLEASANT_SMELL_ODOUR  VARCHAR2(20 BYTE),
  DUST_DIRT               VARCHAR2(20 BYTE),
  DAMAGING_MATERIAL       VARCHAR2(20 BYTE),
  CORE_DAMAGING           VARCHAR2(20 BYTE),
  TENSILE_CD              VARCHAR2(20 BYTE),
  TENSILE_MD              VARCHAR2(20 BYTE),
  VISUAL_INSPECTION       VARCHAR2(20 BYTE),
  STRENGTH                VARCHAR2(20 BYTE),
  STRENGTH_MD             VARCHAR2(20 BYTE)
)-->

------------------------------------------------------------------------------------------------------------------

CREATE TABLE IP_PRODUCT_ITEM_MASTER_SETUP
(
  ITEM_CODE                VARCHAR2(30 BYTE)    NOT NULL,
  ITEM_EDESC               VARCHAR2(1000 BYTE)  NOT NULL,
  ITEM_NDESC               VARCHAR2(100 BYTE),
  CATEGORY_CODE            VARCHAR2(2 BYTE),
  DIMENSION                VARCHAR2(10 BYTE),
  INDEX_MU_CODE            VARCHAR2(8 BYTE),
  FRACTION_VALUE           NUMBER(10,4),
  MASTER_ITEM_CODE         VARCHAR2(30 BYTE)    NOT NULL,
  PRE_ITEM_CODE            VARCHAR2(30 BYTE)    NOT NULL,
  IMAGE_FILE_NAME          VARCHAR2(1000 BYTE),
  SHELF_LIFE_DAYS          NUMBER(5),
  MAX_USAGE                NUMBER(10,2),
  MIN_USAGE                NUMBER(10,2),
  NORMAL_USAGE             NUMBER(10,2),
  MAX_LEVEL                NUMBER(10,2),
  MIN_LEVEL                NUMBER(10,2),
  PREFERRED_LEVEL          NUMBER(10,2),
  REORDER_LEVEL            NUMBER(10,2),
  DANGER_LEVEL             NUMBER(10,2),
  ECO_ORDER_QUANTITY       NUMBER(10,2),
  PREFERRED_SUPPLIER_CODE  VARCHAR2(30 BYTE),
  LEAD_TIME                NUMBER(5),
  COSTING_METHOD_FLAG      CHAR(1 BYTE),
  GROUP_SKU_FLAG           CHAR(1 BYTE),
  HS_CODE                  VARCHAR2(20 BYTE),
  LINK_SUB_CODE            VARCHAR2(30 BYTE),
  REMARKS                  VARCHAR2(200 BYTE),
  COMPANY_CODE             VARCHAR2(30 BYTE)    NOT NULL,
  CREATED_BY               VARCHAR2(30 BYTE)    NOT NULL,
  CREATED_DATE             DATE                 NOT NULL,
  DELETED_FLAG             CHAR(1 BYTE),
  DEFAULT_WIP_STOCK        NUMBER(16,4),
  SERVICE_ITEM_FLAG        CHAR(1 BYTE),
  PURCHASE_PRICE           NUMBER(16,4),
  SALES_PRICE              NUMBER(16,4),
  REMARKS2ND               VARCHAR2(200 BYTE),
  CURRENT_STOCK            NUMBER,
  SYN_ROWID                VARCHAR2(18 BYTE),
  BATCH_FLAG               CHAR(1 BYTE),
  MULTI_MU_CODE            VARCHAR2(5 BYTE),
  SERIAL_FLAG              CHAR(1 BYTE),
  BATCH_SERIAL_FLAG        CHAR(1 BYTE),
  MODIFY_DATE              DATE,
  VALUATION_FLAG           CHAR(1 BYTE),
  BRANCH_CODE              VARCHAR2(30 BYTE),
  PRODUCT_CODE             VARCHAR2(50 BYTE),
  AVG_RATE                 NUMBER,
  MIN_VALUE                NUMBER,
  MAX_VALUE                NUMBER,
  MODIFY_BY                VARCHAR2(30 BYTE),
  REEM_WEIGHT_KG           NUMBER,
  SERIAL_PREFIX_TEXT       VARCHAR2(3 BYTE),
  SERIAL_PREFIX_LENGTH     NUMBER,
  FREEZE_FLAG              CHAR(1 BYTE),
  OPENING_ACC_CODE         VARCHAR2(30 BYTE),
  AUTOM_SERIAL_FLAG        CHAR(1 BYTE),
  STD_RATE                 NUMBER,
  OPENING_FLAG             CHAR(1 BYTE),
  RACK_LOCATION            VARCHAR2(50 BYTE),
  MAIN_FG_CODE             VARCHAR2(30 BYTE),
  NON_VAT_FLAG             CHAR(1 BYTE)         NOT NULL,
  PARTY_TYPE_CODE          VARCHAR2(30 BYTE),
  TARGET                   VARCHAR2(120 BYTE),
  TOLERENCE                VARCHAR2(120 BYTE),
  PRODUCT_TYPE             VARCHAR2(120 BYTE)
)

----------------------------------------------------------------------------------------------------

CREATE TABLE PRE_DISPATCH_INSPECTION
(
  PRE_DISPATCH_INSPECTION_NO   VARCHAR2(20 BYTE) NOT NULL,
  ISDUST_VEHICLE               CHAR(1 BYTE),
  ISWATERSPILL_VEHICLE         CHAR(1 BYTE),
  ISCRACKSHOLES_VEHICLE        CHAR(1 BYTE),
  ISNAILS_VEHICLE              CHAR(1 BYTE),
  ISLEAKWALL_VEHICLE           CHAR(1 BYTE),
  VEHICLE_DUST_REMARKS         VARCHAR2(80 BYTE),
  VEHICLE_WATERSPILL_REMARKS   VARCHAR2(80 BYTE),
  VEHICLE_CRACKSHOLES_REMARKS  VARCHAR2(80 BYTE),
  VEHICLE_NAILS_REMARKS        VARCHAR2(80 BYTE),
  VEHICLE_WALL_REMARKS         VARCHAR2(80 BYTE),
  ISVISUALDEFECT_PRODUCT       CHAR(1 BYTE),
  ISDIMENSIONS_PRODUCT         CHAR(1 BYTE),
  ISWEIGHTCHECK_PRODUCT        CHAR(1 BYTE),
  PRODUCT_DEFECT_REMARKS       VARCHAR2(80 BYTE),
  PRODUCT_DIMENSIONS_REMARKS   VARCHAR2(80 BYTE),
  PRODUCT_WEIGHT_REMARKS       VARCHAR2(80 BYTE),
  ISCORRECT_PACKAGING          CHAR(1 BYTE),
  ISSEALED_PACKAGING           CHAR(1 BYTE),
  ISPERBOX_PACKAGING           CHAR(1 BYTE),
  ISSTACKING_PACKAGING         CHAR(1 BYTE),
  PACKAGING_CORRECT_REMARKS    VARCHAR2(80 BYTE),
  PACKAGING_SEALED_REMARKS     VARCHAR2(80 BYTE),
  PACKAGING_PERBOX_REMARKS     VARCHAR2(80 BYTE),
  PACKAGING_STACKING_REMARKS   VARCHAR2(80 BYTE),
  ISINVOICE_DOCUMENTATION      CHAR(1 BYTE),
  ISQUALITY_DOCUMENTATION      CHAR(1 BYTE),
  ISCOMPLIANCE_DOCUMENTATION   CHAR(1 BYTE),
  DOCU_INVOICE_REMARKS         VARCHAR2(80 BYTE),
  DOCU_QUALITY_REMARKS         VARCHAR2(80 BYTE),
  DOCU_COMP_REMARKS            VARCHAR2(80 BYTE),
  COMPANY_CODE                 VARCHAR2(30 BYTE) NOT NULL,
  BRANCH_CODE                  VARCHAR2(30 BYTE) NOT NULL,
  CREATED_BY                   VARCHAR2(30 BYTE) NOT NULL,
  CREATED_DATE                 DATE             NOT NULL,
  DELETED_FLAG                 CHAR(1 BYTE),
  MODIFY_DATE                  DATE,
  MODIFY_BY                    VARCHAR2(30 BYTE),
  SERIAL_NO                    VARCHAR2(10 BYTE),
  FORM_CODE                    VARCHAR2(10 BYTE) NOT NULL
)

-------------------------------------------------------------------------------------------------------

CREATE TABLE IP_ITEM_QC_PARAMETER_MASTER
(
  PARAM_CODE    VARCHAR2(30 BYTE)               NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE),
  SYN_ROWID     VARCHAR2(18 BYTE),
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE),
  PRODUCT_TYPE  VARCHAR2(120 BYTE),
  TYPE          VARCHAR2(20 BYTE)
)

---------------------------------------------------------------------------------------------------------

CREATE TABLE IP_ITEM_QC_PARAMETER_DETAILS
(
  SERIAL_NO      VARCHAR2(10 BYTE)              NOT NULL,
  PARAM_CODE     VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  PARAMETERS     VARCHAR2(100 BYTE),
  TARGET         VARCHAR2(120 BYTE),
  TOLERENCE      VARCHAR2(120 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE),
  SPECIFICATION  VARCHAR2(100 BYTE),
  PRODUCT_TYPE   VARCHAR2(120 BYTE)
)

-----------------------------------------------------------------------------------------------------------

CREATE TABLE SANITATIONHYGIENE
(
  SERIAL_NO        VARCHAR2(10 BYTE)            NOT NULL,
  SANITATION_NO    VARCHAR2(30 BYTE)            NOT NULL,
  DEPARTMENT_CODE  VARCHAR2(30 BYTE)            NOT NULL,
  STANDARD         VARCHAR2(10 BYTE),
  ACTUAL           VARCHAR2(10 BYTE),
  GAP              VARCHAR2(10 BYTE),
  COMPANY_CODE     VARCHAR2(30 BYTE)            NOT NULL,
  BRANCH_CODE      VARCHAR2(30 BYTE)            NOT NULL,
  CREATED_BY       VARCHAR2(30 BYTE)            NOT NULL,
  CREATED_DATE     DATE                         NOT NULL,
  DELETED_FLAG     CHAR(1 BYTE),
  SYN_ROWID        VARCHAR2(18 BYTE),
  MODIFY_DATE      DATE,
  MODIFY_BY        VARCHAR2(30 BYTE)
)



-------------------------------------------------------------------------------
FormSetup Table
---------
Note :- Module code and Form Code may be different according to database. Please take max +1 module code and Form Code

Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('500', 'Daily Wastage Report', 'Daily Wastage Report', '17.00.00', '17.00.00', 
    '08', 'I', 'QC-DW/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'DW', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('503', 'Global Agro Products', 'Global Agro Products', '17.00.00', '17.00.00', 
    '08', 'I', 'QC-GP/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'GP', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('501', 'Handover Inspection Report', 'Handover Inspection Report', '18.00.00', '18.00.00', 
    '08', 'I', 'QC-HO/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'HO', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('506', 'Sanitation Hygiene', 'Sanitation Hygiene', '21.00.00', '21.00.00', 
    '08', 'I', 'QC-SH/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'SH', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('508', 'FINISHED GOODS INSPECTION', 'FINISHED GOODS INSPECTION', '23.00.00', '23.00.00', 
    '08', 'I', 'QC-FI/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'FI', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('505', 'Internal Inspection', 'Internal Inspection', '20.00.00', '20.00.00', 
    '08', 'I', 'QC-II/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'II', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('496', 'Incoming Material', 'Incoming Material', '08.00.00', '08.00', 
    '08', 'I', 'QC-IN/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'IN', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('789', 'Quality Control Group', 'Quality Control', '08.00', '00', 
    '08', 'G', 'QC-DW/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'QC', TO_DATE('2025-9-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('509', 'Incoming Material(Sample)', 'Incoming Material(Sample)', '24.00.00', '24.00.00', 
    '08', 'I', 'QC-IS/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'IS', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('499', 'Daily Raw Material', 'Daily Raw Material', '16.00.00', '16.00.00', 
    '08', 'I', 'QC-RM/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'RM', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('504', 'On Site Inspection', 'On Site Inspection', '19.00.00', '19.00.00', 
    '08', 'I', 'QC-OI/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'OI', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('507', 'PRE DISPATCH INSPECTION', 'PRE DISPATCH INSPECTION', '22.00.00', '22.00.00', 
    '08', 'I', 'QC-PD/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'PD', TO_DATE('2025-5-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
Insert into FORM_SETUP
   (FORM_CODE, FORM_EDESC, FORM_NDESC, MASTER_FORM_CODE, PRE_FORM_CODE, 
    MODULE_CODE, GROUP_SKU_FLAG, CUSTOM_PREFIX_TEXT, CUSTOM_SUFFIX_TEXT, PREFIX_LENGTH, 
    SUFFIX_LENGTH, BODY_LENGTH, START_NO, LAST_NO, START_DATE, 
    LAST_DATE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    FORM_TYPE, MODIFY_DATE, MODIFY_BY, VNO_AS_DOC_ID_CONTROL, DEFAULT_SHIPMENT, 
    RECEIPT_FLAG, NON_RETURN_FLAG, DISPLAY_RATE, EMAIL_FLAG, DEACTIVATE_TAXABLE_RATE_FLAG, 
    AUTO_CONV_FLAG, PROD_IO_EQUAL_FLAG, QR_FLAG, CALL_API, MAX_ROWS)
 Values
   ('498', 'Quality Control', 'Quality Control', '08.00.00', '08.00', 
    '08', 'I', 'QC-DW/', '/81-82', 6, 
    6, 5, 1, 986677, TO_DATE('2025-2-2', 'YYYY-MM-DD'), 
    TO_DATE('2025-4-30', 'YYYY-MM-DD'), '01', 'admin', TO_DATE('2025-3-24', 'YYYY-MM-DD'), 'N', 
    'QC', TO_DATE('2025-9-7', 'YYYY-MM-DD'), 'admin', 'N', 'None', 
    'N', 'N', 'N', 'N', 'N', 
    'Y', 'N', 'N', 'N', 0);
COMMIT;


------------------------------------------------------------------------------------
Form Detail Setup Table
-----------------------
1)
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (38, 'IP_ITEM_QC_SETUP', 'ROLL3', 3300, 'ROLL3', 
    880, 1605, 'Y', 'N', 'M', 
    '496', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (39, 'IP_ITEM_QC_SETUP', 'QC_SPECIFICATION', 3300, 'QC_SPECIFICATION', 
    880, 1605, 'Y', 'N', 'M', 
    '496', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (43, 'IP_ITEM_QC_SETUP', 'GSM', 3300, 'GSM', 
    880, 1605, 'Y', 'N', 'C', 
    '496', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (44, 'IP_ITEM_QC_SETUP', 'SIZE_WIDTH', 3300, 'Width', 
    880, 1605, 'Y', 'N', 'C', 
    '496', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (45, 'IP_ITEM_QC_SETUP', 'STRENGTH', 3300, 'Strength', 
    880, 1605, 'Y', 'N', 'C', 
    '496', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (46, 'IP_ITEM_QC_SETUP', 'THICKNESS', 3300, 'Thickness', 
    880, 1605, 'Y', 'N', 'C', 
    '496', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (51, 'IP_ITEM_QC_SETUP', 'REMARKS', 1200, 'Remarks', 
    880, 1605, 'Y', 'N', 'C', 
    '496', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (36, 'IP_ITEM_QC_SETUP', 'ROLL1', 3300, 'ROLL1', 
    880, 1605, 'Y', 'N', 'M', 
    '496', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (37, 'IP_ITEM_QC_SETUP', 'ROLL2', 3300, 'ROLL2', 
    880, 1605, 'Y', 'N', 'M', 
    '496', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;

2)
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (15, 'IP_ITEM_QC_TESTING', 'REMARKS', 1200, 'Remarks', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (1, 'IP_ITEM_QC_TESTING', 'item_edesc', 12000, 'Raw Material Name', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (2, 'IP_ITEM_QC_TESTING', 'SUPPLIER_EDESC', 3300, 'Vendor Name', 
    880, 8000, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (3, 'IP_ITEM_QC_TESTING', 'BATCH_NO', 3300, 'Batch No', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (10, 'IP_ITEM_QC_TESTING', 'ACTUAL_GSM', 3300, 'GSM', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (11, 'IP_ITEM_QC_TESTING', 'ACTUAL_SIZE_WIDTH', 3300, 'Width', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (12, 'IP_ITEM_QC_TESTING', 'ACTUAL_MD_STRENGTH', 3300, 'MD Strength', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (14, 'IP_ITEM_QC_TESTING', 'ACTUAL_THICKNESS', 3300, 'Thickness', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (5, 'IP_ITEM_QC_TESTING', 'GSM', 3300, 'GSM', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (6, 'IP_ITEM_QC_TESTING', 'SIZE_WIDTH', 3300, 'Width', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (7, 'IP_ITEM_QC_TESTING', 'MD_STRENGTH', 5300, 'MD Strength', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (9, 'IP_ITEM_QC_TESTING', 'THICKNESS', 3300, 'Thickness', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (8, 'IP_ITEM_QC_TESTING', 'CD_STRENGTH', 3300, 'CD Strength', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (13, 'IP_ITEM_QC_TESTING', 'ACTUAL_CD_STRENGTH', 3300, 'CD Strength', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (4, 'IP_ITEM_QC_TESTING', 'Roll_no', 1200, 'Roll No', 
    880, 1605, 'Y', 'N', 'C', 
    '499', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;

3)
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (4, 'IP_ITEM_DAILY_WASTAGE', 'QTY', 1200, 'QTY', 
    880, 1605, 'Y', 'N', 'C', 
    '500', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (1, 'IP_ITEM_DAILY_WASTAGE', 'ITEM_CODE', 1200, 'Daily Wastage Report', 
    880, 1605, 'N', 'N', 'C', 
    '500', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (3, 'IP_ITEM_DAILY_WASTAGE', 'UNIT', 1200, 'UNIT', 
    880, 1605, 'Y', 'N', 'C', 
    '500', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (2, 'IP_ITEM_DAILY_WASTAGE', 'ITEM_EDESC', 1200, 'Daily Wastage Report', 
    880, 1605, 'Y', 'N', 'C', 
    '500', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;

4)
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (1, 'HANDOVER_INSPECTION', 'TIME_PERIOD', 1200, 'Time Period', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (5, 'HANDOVER_INSPECTION', 'BATCH_NO', 1200, 'Batch No', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (6, 'HANDOVER_INSPECTION', 'LOOSE_PRODUCT_SAMPLE', 1200, 'Sample', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (7, 'HANDOVER_INSPECTION', 'LOOSE_PRODUCT_DEFECT', 1200, 'Defect', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (8, 'HANDOVER_INSPECTION', 'UNSEALED_PACKET_SAMPLE', 1200, 'Sample', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (9, 'HANDOVER_INSPECTION', 'UNSEALED_PACKET_DEFECT', 1200, 'Defect', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (10, 'HANDOVER_INSPECTION', 'SEALED_PACKET_SAMPLE', 1200, 'Sample', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (11, 'HANDOVER_INSPECTION', 'SEALED_PACKET_DEFECT', 1200, 'Defect', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (12, 'HANDOVER_INSPECTION', 'BAG_SAMPLE', 1200, 'Sample', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (13, 'HANDOVER_INSPECTION', 'BAG_DEFECT', 1200, 'Defect', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (14, 'HANDOVER_INSPECTION', 'WRAPPER_SAMPLE', 1200, 'Sample', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (15, 'HANDOVER_INSPECTION', 'WRAPPER_DEFECT', 1200, 'Defect', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (16, 'HANDOVER_INSPECTION', 'REMARKS', 1200, 'Remarks', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (2, 'HANDOVER_INSPECTION', 'PRODUCT_TYPE', 1200, 'Product Type', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (4, 'HANDOVER_INSPECTION', 'ITEM_EDESC', 1200, 'Product Name', 
    880, 1605, 'Y', 'N', 'C', 
    '501', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;


5)

Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (1, 'ONSITEINSPECTIONS', 'PARAMETERS', 3300, 'PARAMETERS', 
    880, 1605, 'Y', 'N', 'C', 
    '504', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (2, 'ONSITEINSPECTIONS', 'TARGET', 3300, 'PARAMETERS', 
    880, 1605, 'Y', 'N', 'C', 
    '504', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (3, 'ONSITEINSPECTIONS', 'TOLERENCE', 3300, 'PARAMETERS', 
    880, 1605, 'Y', 'N', 'C', 
    '504', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (4, 'ONSITEINSPECTIONS', 'RESULTS', 3300, 'PARAMETERS', 
    880, 1605, 'Y', 'N', 'C', 
    '504', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (5, 'ONSITEINSPECTIONS', 'VARIANCE', 3300, 'PARAMETERS', 
    880, 1605, 'Y', 'N', 'C', 
    '504', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;


6)
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (1, 'INTERNALINSPECTION', 'PARAMETERS', 3300, 'PARAMETERS', 
    880, 1605, 'Y', 'N', 'C', 
    '505', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (2, 'INTERNALINSPECTION', 'SPECIFICATION', 3300, 'SPECIFICATION', 
    880, 1605, 'Y', 'N', 'C', 
    '505', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (3, 'INTERNALINSPECTION', 'UNIT', 3300, 'UNIT', 
    880, 1605, 'Y', 'N', 'C', 
    '505', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (4, 'INTERNALINSPECTION', 'TARGET', 3300, 'TARGET', 
    880, 1605, 'Y', 'N', 'C', 
    '505', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (5, 'INTERNALINSPECTION', 'TOLERENCE', 3300, 'TOLERENCE', 
    880, 1605, 'Y', 'N', 'C', 
    '505', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (6, 'INTERNALINSPECTION', 'RESULTS', 3300, 'RESULTS', 
    880, 1605, 'Y', 'N', 'C', 
    '505', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (7, 'INTERNALINSPECTION', 'VARIANCE', 3300, 'VARIANCE', 
    880, 1605, 'Y', 'N', 'C', 
    '505', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;

7)
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (1, 'SANITATIONHYGIENE', 'DEPARTMENT_CODE', 3300, 'DEPARTMENT', 
    880, 1605, 'Y', 'N', 'C', 
    '506', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (3, 'SANITATIONHYGIENE', 'ACTUAL', 3300, 'ACTUAL', 
    880, 1605, 'Y', 'N', 'C', 
    '506', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (2, 'SANITATIONHYGIENE', 'STANDARD', 3300, 'STANDARD', 
    880, 1605, 'Y', 'N', 'C', 
    '506', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (4, 'SANITATIONHYGIENE', 'GAP', 3300, 'GAP', 
    880, 1605, 'Y', 'N', 'C', 
    '506', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;

8)
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (1, 'PRE_DISPATCH_INSPECTION', 'ISDUST_VEHICLE', 3300, 'DUST VEHICLE', 
    880, 1605, 'Y', 'N', 'M', 
    '507', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;

9)
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (1, 'FINISH_GOODS_INSP', 'PACK_CONDITION', 3300, 'PACK_CONDITION', 
    880, 1605, 'Y', 'N', 'M', 
    '508', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;

10)
Insert into FORM_DETAIL_SETUP
   (SERIAL_NO, TABLE_NAME, COLUMN_NAME, COLUMN_WIDTH, COLUMN_HEADER, 
    TOP_POSITION, LEFT_POSITION, DISPLAY_FLAG, IS_DESC_FLAG, MASTER_CHILD_FLAG, 
    FORM_CODE, COMPANY_CODE, CREATED_BY, CREATED_DATE, DELETED_FLAG, 
    HELP_DESCRIPTION)
 Values
   (1, 'IP_ITEM_QC_SETUP', 'ROLL3', 3300, 'ROLL3', 
    880, 1605, 'Y', 'N', 'M', 
    '509', '01', 'ADMIN', TO_DATE('2024-11-14 14:09:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', 
    'HELP_DESCRIPTION');
COMMIT;




